import {
  createContext,
  useContext,
  useEffect,
  useLayoutEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

export type Locale = "en" | "zh-CN";
export type Theme = "light" | "dark";

export const preferenceStorageKeys = {
  locale: "skill-reviewer.locale",
  theme: "skill-reviewer.theme",
} as const;

const englishMessages = {
  pageTitle: "Skill Reviewer · Evidence Workbench",
  appTitle: "Skill Reviewer evidence workspace",
  brandEvidence: "Evidence",
  displayPreferences: "Display preferences",
  language: "Language",
  switchToEnglish: "Switch to English",
  switchToChinese: "Switch to Simplified Chinese",
  switchToDarkTheme: "Switch to dark theme",
  switchToLightTheme: "Switch to light theme",
  darkTheme: "Dark",
  lightTheme: "Light",
  openCommandPalette: "Go to evidence",
  commandPaletteTitle: "Go to evidence",
  commandPalettePlaceholder: "Search cases, evidence, files, and commands",
  closeCommandPalette: "Close command palette",
  commandsAvailable: "Available commands",
  noCommandsFound: "No matching destination",
  noCommandsHint: "Try a case ID, evidence label, file path, or action.",
  navigate: "navigate",
  runCommand: "open",
  close: "close",
  actionGroup: "Action",
  caseGroup: "Case",
  evidenceGroup: "Evidence",
  fileGroup: "File",
  copyViewLink: "Copy view link",
  downloadEvidenceJson: "Download projection JSON",
  viewLinkCopied: "View link copied",
  viewLinkCopyFailed: "View link could not be copied",
  evidenceJsonDownloaded: "Projection JSON download started",
  evidenceJsonDownloadFailed: "Projection JSON could not be downloaded",
  showEvidence: "Show evidence chain",
  showDiff: "Show document diff",
  showActionCenter: "Open action center",
  showAttention: "Show cases needing attention",
  showAllCases: "Show all cases",
  useDarkTheme: "Use dark theme",
  useLightTheme: "Use light theme",
  useChinese: "Use Simplified Chinese",
  useEnglish: "Use English",
  live: "Live",
  connecting: "Connecting",
  stale: "Stale",
  readOnly: "read-only",
  behavioralGateState: "Behavioral gate state",
  releaseState: "Release decision",
  releaseReady: "Ready for release",
  releaseBlockedTitle: "Not ready for release",
  releaseReadySummary: "All required scenarios and release gates passed.",
  releaseBlockedSummary: "{cases} scenarios and {gates} release gates still need attention.",
  releaseBlockedGenericSummary: "Required evidence or audit conditions are still incomplete.",
  runSummary: "Run summary",
  hardGates: "Hard gates",
  casesPassed: "Cases passed",
  round: "Round",
  evidence: "Evidence",
  evidenceScope: "Evidence scope",
  inputsLocked: "Inputs locked",
  integrityPending: "Integrity pending",
  releaseEligible: "behaviorally release-eligible",
  releaseBlocked: "behavioral evidence blocked",
  runOverview: "Run overview",
  evaluationSuite: "Evaluation suite",
  cases: "Cases",
  split: "Split",
  searchCases: "Search cases",
  filterCases: "Filter cases",
  caseStatus: "Scenario result",
  attention: "Needs attention",
  caseFilterOption: "{label}; matching scenario count: {count}",
  caseFilterScope: "This filter counts evaluation scenarios only; release gates are listed separately in the evidence tree.",
  noCasesMatch: "No cases match this view.",
  clearFilters: "Clear filters",
  caseResults: "{count} of {total} cases",
  all: "All",
  development: "Development",
  selection: "Selection",
  audit: "Audit",
  pairedRuns: "{count}× paired",
  noCasesInSplit: "No cases in this split.",
  evolution: "Evolution",
  continuitySummary: "continuity epoch {epoch} · {count} rejected",
  candidateLineage: "Candidate lineage",
  lineageRound: "Round {round}",
  evidenceWorkspace: "Evidence workspace",
  canvasView: "Canvas view",
  diff: "Diff",
  retainedNodes: "{count} retained nodes",
  displayedEvidenceNodes: "Showing {visible} of {total} evidence nodes",
  runtimeFilesChanged: "{count} runtime files changed",
  actionCenterContext: "Next: {action} · owned by the lead Agent",
  enterDiffFocus: "Enter diff focus mode",
  exitDiffFocus: "Exit diff focus mode",
  focusOnDiff: "Focus on diff",
  exitFocus: "Exit focus mode",
  immutableRunRecord: "Immutable run record",
  evidenceChain: "Evidence chain",
  evidenceChainDescription: "Start with the release decision, open a failed scenario, inspect its failed check, then read the source evidence.",
  firstReviewGuide: "First review: decision → failed scenario → failed check → source evidence",
  blockingEvidenceFlow: "Current blocker: {cases} scenarios needing attention → {gates} failed release gates",
  blockingEvidenceExplanation: "Release gates summarize scenario evidence. The same blocking issue can appear at both levels, but it still counts as one scenario.",
  evidenceTreeControls: "Evidence hierarchy controls",
  evidenceHierarchy: "Evidence hierarchy",
  expandAllEvidence: "Expand all",
  collapseAllEvidence: "Collapse all",
  expandEvidence: "Expand {label}",
  collapseEvidence: "Collapse {label}",
  statusLegend: "Status legend",
  passed: "Passed",
  pending: "Pending",
  blocked: "Blocked",
  openEvidence: "Open evidence {label}",
  viewEvidenceDetails: "View details for {label}",
  viewDetails: "View details",
  childItems: "{count} items",
  repeatMeta: "repeat {count}",
  retainedEvidenceRecord: "Retained evidence record",
  loadingDiffRenderer: "Loading diff renderer…",
  noRuntimeChanges: "No runtime changes",
  candidateMatchesRuntime: "The candidate matches the accepted runtime surface.",
  evidenceInspector: "Evidence inspector",
  inspector: "Review guide",
  retainedEvidenceDescription: "Retained evidence from the immutable run workspace.",
  currentFinding: "Current finding",
  decisionBasis: "Why this result",
  nextReviewStep: "Next review step",
  viewBasisEvidence: "View evidence",
  whyItMatters: "Why this exists",
  evidenceInputs: "What it reads",
  reviewerChecklist: "What a human should verify",
  automatedDecision: "How the automated check decided",
  checkRule: "Declared rule",
  observedResult: "Observed result",
  importance: "Decision impact",
  sourceEvidence: "Source evidence",
  sourceEvidenceDescription: "The exact retained content read by this check or cited by this decision.",
  loadingSourceEvidence: "Loading retained evidence…",
  sourceEvidenceUnavailable: "Source content is not available in this view.",
  sourceEvidenceLoadFailed: "The retained content could not be loaded or no longer matches its bound digest.",
  opaqueEvidence: "Content is hidden because this is an opaque audit scenario. The boundary prevents the evolution loop from tuning against holdout evidence.",
  binaryEvidence: "This retained artifact is binary and is verified by digest instead of being rendered.",
  oversizedEvidence: "This retained artifact is larger than the safe inline-reader limit. Its digest and path remain available in technical trace.",
  expandSourceContent: "Expand content",
  collapseSourceContent: "Collapse content",
  contentTruncated: "Preview truncated at the bounded reader limit; the full file remains bound by digest.",
  evidenceSize: "{size} retained bytes",
  evidenceId: "Evidence ID",
  arm: "Arm",
  repeat: "Repeat",
  assertion: "Assertion",
  artifactPath: "Artifact path",
  decisionArtifact: "Decision artifact",
  technicalTrace: "Technical trace",
  technicalName: "Internal name",
  pairedArms: "Paired arms",
  missingObjectiveMetrics: "Missing objective metrics: {metrics}",
  assertionsSummary: "{passed}/{total} assertions · {rate}",
  bindingSummary: "{binding} binding · {forbidden} forbidden · {effects} side effects",
  semanticEvidence: "Semantic evidence",
  preference: "preference {value}",
  unresolved: "unresolved",
  provenance: "Execution context",
  subject: "Subject",
  subjectFingerprint: "Reviewed Skill fingerprint",
  baseline: "Baseline",
  baselineFingerprint: "Baseline fingerprint",
  plan: "Plan",
  profile: "Profile",
  target: "Target",
  harness: "Harness",
  holdout: "Holdout",
  controlAnchor: "Control anchor",
  none: "none",
  unknown: "unknown",
  public: "public",
  notUsed: "not used",
  notRecorded: "not recorded",
  selectEvidence: "Select an evidence record.",
  limitations: "Limitations",
  noLimitations: "No recorded limitations.",
  refreshEvery: "refresh {seconds}s",
  generatedAt: "Generated {time}",
  checkedAt: "Checked {time}",
  loadedAt: "Loaded {time}",
  attemptedAt: "Attempted {time}",
  generationTimeUnavailable: "Generation time unavailable",
  notChecked: "Not checked yet",
  pauseAutoRefresh: "Pause automatic refresh",
  resumeAutoRefresh: "Resume automatic refresh",
  refreshDashboard: "Refresh dashboard now",
  refreshing: "Refreshing evidence",
  autoRefreshOn: "Auto-refresh on",
  autoRefreshPaused: "Auto-refresh paused",
  lastRefreshFailed: "Last refresh failed",
  retainedJsonArtifacts: "retained JSON artifacts",
  evidenceDataLoaded: "evidence data loaded",
  connectingToEvidence: "Connecting to evidence",
  waitingForData: "Waiting for dashboard-data.json…",
  evidenceUnavailable: "Evidence is unavailable",
  retryConnection: "Retry connection",
  retryHelp: "Check that the read-only dashboard server is running, then retry.",
  runMismatchTitle: "This link targets a different run",
  runMismatchBody: "Requested {requested}; this server is presenting {current}.",
  openCurrentRun: "Open the current run",
  skipToEvidence: "Skip to evidence workspace",
  copyEvidenceReference: "Copy evidence reference",
  evidenceReference: "Skill Reviewer evidence reference",
  semanticSummary: "Meaning",
  evidenceReferenceCopied: "Evidence reference copied",
  evidenceReferenceCopyFailed: "Evidence reference could not be copied",
  status: "Status",
  permalink: "Permalink",
  changedFiles: "Changed files",
  changedFileTree: "Changed files",
  changedFilesRoot: "SKILL-REVIEWER",
  expandChangedFilesRoot: "Expand changed file root",
  collapseChangedFilesRoot: "Collapse changed file root",
  filterChangedFiles: "Filter changed files",
  filterFiles: "Filter files",
  changedRuntimeFiles: "Changed runtime files",
  changedRuntimeFileTree: "Changed runtime file tree",
  expandDirectory: "Expand directory {name}",
  collapseDirectory: "Collapse directory {name}",
  directoryFileCount: "{count} files",
  openDiff: "Open diff {path}",
  noChangedFilesMatch: "No changed files match “{query}”.",
  documentDiff: "Document diff",
  noFileSelected: "No file selected",
  fileNavigation: "File navigation",
  previousChangedFile: "Previous changed file",
  previousFile: "Previous file",
  nextChangedFile: "Next changed file",
  nextFile: "Next file",
  diffLayout: "Diff layout",
  splitDiff: "Split diff",
  unifiedDiff: "Unified diff",
  wrapLines: "Wrap lines",
  wrapLongLines: "Wrap long lines",
  chooseChangedFile: "Choose a changed file to inspect.",
  previewUnavailable: "Preview unavailable",
  sizeSummary: "Old {oldSize} · new {newSize}",
  loadingPreview: "Loading bounded preview…",
  diffRenderFailed: "Diff could not be rendered",
  diffIntegrityFailed: "Diff integrity check failed",
  retryDiffPreview: "Retry preview",
  copyDiagnostics: "Copy diagnostics",
  diagnosticsCopied: "Diagnostics copied",
  diagnosticsCopyFailed: "Diagnostics could not be copied",
  lineSummary: "{oldLines} → {newLines} lines",
  actionCenter: "Action center",
  humanDecisionHandoff: "Evidence-bound decision handoff",
  actionCenterDescription: "Decide whether the candidate is acceptable, identify the accountable layer, then create one auditable task for the lead Agent.",
  currentStateAndNextAction: "Current state and projected next action",
  currentState: "Current state",
  stateMachineNextAction: "State-machine next action",
  nextActionStop: "Stop continuous evolution",
  nextActionReviewEvidence: "Review the current evidence",
  leadAgentOwner: "Lead Agent owns execution",
  candidateAcceptability: "Can this candidate be accepted?",
  candidateAcceptabilityDescription: "Selection requires all three conditions at once; one failure rejects the candidate.",
  criterion_hard_gates: "Hard gates",
  criterion_hard_gates_description: "Required assertions, paired evidence, and safety checks must all pass.",
  criterion_pareto: "Pareto admissibility",
  criterion_pareto_description: "No declared objective may regress beyond its tolerance.",
  criterion_material_improvement: "Material improvement",
  criterion_material_improvement_description: "At least one primary objective must improve by its declared minimum delta.",
  awaitingEvidence: "awaiting evidence",
  candidateVerdict: "Candidate verdict",
  allAcceptanceConditionsMet: "All three selection conditions are satisfied.",
  acceptanceConditionsNotMet: "At least one required selection condition is not satisfied.",
  acceptancePendingEvidence: "There is not enough retained evidence to decide yet.",
  failureAttribution: "Who owns the blocker?",
  primaryAttributionSummary: "Primary attribution: {owner}",
  noFailureAttributed: "No failure is currently attributable.",
  attribution_skill: "Skill behavior",
  attribution_skill_description: "The candidate's instructions or behavior failed a required outcome, safety rule, or objective.",
  attribution_eval: "Eval design",
  attribution_eval_description: "The scenario, metric, or assertion contract cannot support the intended decision.",
  attribution_execution_environment: "Execution environment",
  attribution_execution_environment_description: "The bound inputs, harness, or runtime prevented a trustworthy execution.",
  attribution_evidence: "Missing evidence",
  attribution_evidence_description: "Required candidate or baseline artifacts are absent or incomplete.",
  attribution_human: "Human decision",
  attribution_human_description: "The automated chain has reached an explicit authorization or release boundary.",
  attributionStatus_primary: "primary",
  attributionStatus_contributing: "contributing",
  attributionStatus_clear: "no signal",
  attributionStatus_waiting: "waiting for decision",
  noAttributionSignal: "No matching signal in the retained evidence.",
  openAttributionEvidence: "Open supporting evidence",
  signal_binding_error: "Execution inputs do not match the locked plan.",
  signal_candidate_evidence_incomplete: "Candidate artifacts are incomplete.",
  signal_required_assertion_failed: "A required candidate assertion failed.",
  signal_unsafe_behavior_observed: "A forbidden action or external side effect was observed.",
  signal_objective_regressed: "A declared objective regressed.",
  signal_stochastic_direction_disagreement: "Repeated runs disagree on the direction of the result.",
  signal_objective_metric_unavailable: "An objective metric is unavailable in paired evidence.",
  signal_baseline_evidence_incomplete: "The paired baseline is incomplete.",
  signal_pareto_regression: "The candidate is not Pareto-admissible.",
  signal_material_improvement_missing: "No primary objective improved materially.",
  signal_objective_evidence_missing: "No usable objective evidence was produced.",
  signal_declared_metric_missing: "A metric required by the eval contract is missing.",
  signal_paired_evidence_missing: "A required paired comparison is missing.",
  signal_audit_authorization_required: "A human must authorize the one-shot audit.",
  signal_release_confirmation_required: "A human must confirm release after audit.",
  unknownAttributionSignal: "An additional machine signal was recorded; inspect the technical trace.",
  recommendedActions: "Recommended action",
  recommendedActionsDescription: "Availability comes from the state machine. Buttons create tasks; they do not execute work or change evidence.",
  action_generate_candidate: "Generate the next candidate",
  action_generate_candidate_description: "Ask the lead Agent to use the failed evidence and lineage to propose another Skill candidate.",
  action_rerun_execution: "Run or rerun the authorized execution",
  action_rerun_execution_description: "Ask the lead Agent to dispatch the already authorized plan and retain fresh artifacts.",
  action_propose_eval_change: "Submit an eval change proposal",
  action_propose_eval_change_description: "Draft a reviewable suggestion for the immutable eval; applying it still requires explicit user confirmation and a new lock.",
  action_authorize_audit: "Request audit authorization",
  action_authorize_audit_description: "Create a human-decision task for the one-shot opaque audit; this does not grant authorization itself.",
  action_request_release_confirmation: "Request release confirmation",
  action_request_release_confirmation_description: "Create the final human-decision task after the audit has passed.",
  recommended: "Recommended",
  humanConfirmationBoundary: "Human confirmation remains mandatory; this task cannot cross the boundary by itself.",
  creatingTask: "Creating task…",
  createLeadAgentTask: "Create lead-Agent task",
  notAvailableInCurrentState: "Not available in this state",
  actionTaskCreateFailed: "The task was not created. The run may have advanced; refresh and review the current state.",
  taskAuditTrail: "Action task audit trail",
  refreshTaskAudit: "Refresh",
  loadingTaskAudit: "Loading the external task ledger…",
  taskAuditUnavailable: "The task ledger is unavailable; evidence remains readable and unchanged.",
  noActionTasks: "No action task has been requested for this run.",
  taskOwnedByLeadAgent: "owned by lead Agent",
  taskRequested: "Requested",
  nextActionComesFromStateMachine: "This value is projected from the validated evolution state, not inferred by the UI.",
  executionOwner: "Execution owner",
  leadAgentOwnerDescription: "The dashboard records intent only. The lead Agent validates the precondition, dispatches workers if needed, and retains the resulting evidence.",
  whenCreatingTask: "What happens when you click",
  taskStepSnapshot: "Bind the request to this run and the exact dashboard digest.",
  taskStepPrecondition: "Require the expected next_action to still match.",
  taskStepAudit: "Append a digest-chained task outside the evidence workspace.",
  taskStepAgent: "Let the lead Agent consume the task; never execute from the browser.",
  controlBoundary: "Control boundary",
  evidenceRemainsReadOnly: "Run evidence stays read-only",
  evidenceRemainsReadOnlyDescription: "No action request can edit execution plans, artifacts, decisions, or the projection.",
  evalRemainsImmutable: "evals.json stays immutable",
  evalRemainsImmutableDescription: "An eval action creates a proposal only; the user must approve any future change.",
  rootDirectory: "root",
} as const;

export type MessageKey = keyof typeof englishMessages;
type MessageValues = Record<string, string | number>;

const chineseMessages: Record<MessageKey, string> = {
  pageTitle: "Skill Reviewer · 证据工作台",
  appTitle: "Skill Reviewer 证据工作台",
  brandEvidence: "证据",
  displayPreferences: "显示偏好",
  language: "语言",
  switchToEnglish: "切换到英文",
  switchToChinese: "切换到中文",
  switchToDarkTheme: "切换到深色主题",
  switchToLightTheme: "切换到浅色主题",
  darkTheme: "深色",
  lightTheme: "浅色",
  openCommandPalette: "查找场景或证据",
  commandPaletteTitle: "查找场景或证据",
  commandPalettePlaceholder: "输入场景名称、内部 ID、文件路径或操作",
  closeCommandPalette: "关闭命令面板",
  commandsAvailable: "可用命令",
  noCommandsFound: "没有匹配的目标",
  noCommandsHint: "可尝试输入场景名称、内部 ID、证据名称或文件路径。",
  navigate: "定位",
  runCommand: "打开",
  close: "关闭",
  actionGroup: "操作",
  caseGroup: "场景",
  evidenceGroup: "证据",
  fileGroup: "文件",
  copyViewLink: "复制当前视图链接",
  downloadEvidenceJson: "下载当前评测数据",
  viewLinkCopied: "当前视图链接已复制",
  viewLinkCopyFailed: "无法复制当前视图链接",
  evidenceJsonDownloaded: "已开始下载评测数据",
  evidenceJsonDownloadFailed: "无法下载评测数据",
  showEvidence: "查看评测证据",
  showDiff: "查看 Skill 文件变更",
  showActionCenter: "打开行动中心",
  showAttention: "只看需要处理的场景",
  showAllCases: "显示全部评测场景",
  useDarkTheme: "使用深色主题",
  useLightTheme: "使用浅色主题",
  useChinese: "使用简体中文",
  useEnglish: "使用英文",
  live: "实时",
  connecting: "连接中",
  stale: "已过期",
  readOnly: "只读查看",
  behavioralGateState: "发布证据概览",
  releaseState: "发布结论",
  releaseReady: "可以进入发布",
  releaseBlockedTitle: "暂不可发布",
  releaseReadySummary: "全部必检场景与发布门禁均已通过。",
  releaseBlockedSummary: "{cases} 个场景、{gates} 项发布门禁尚未通过。",
  releaseBlockedGenericSummary: "仍有必需证据或审计条件未满足，请查看需关注项。",
  runSummary: "评测概览",
  hardGates: "发布门禁",
  casesPassed: "场景通过",
  round: "演进轮次",
  evidence: "证据",
  evidenceScope: "证据范围",
  inputsLocked: "评测输入已锁定",
  integrityPending: "完整性待确认",
  releaseEligible: "现有行为证据支持发布",
  releaseBlocked: "尚未满足发布条件",
  runOverview: "评测概览",
  evaluationSuite: "评测场景",
  cases: "评测场景",
  split: "评测阶段",
  searchCases: "搜索场景",
  filterCases: "按名称或 ID 筛选",
  caseStatus: "按场景结果",
  attention: "需处理场景",
  caseFilterOption: "{label}；匹配场景数：{count}",
  caseFilterScope: "此处只筛选和统计评测场景；发布门禁会在中间证据树中单独展示。",
  noCasesMatch: "当前视图没有匹配的场景。",
  clearFilters: "清除筛选",
  caseResults: "当前显示 {count} / {total} 个场景",
  all: "全部",
  development: "开发验证",
  selection: "发布选拔",
  audit: "安全审计",
  pairedRuns: "{count} 轮候选/旧版对照",
  noCasesInSplit: "当前评测阶段没有场景。",
  evolution: "连续演进",
  continuitySummary: "连续演进周期 {epoch} · 已淘汰 {count} 个候选",
  candidateLineage: "候选演进记录",
  lineageRound: "第 {round} 轮",
  evidenceWorkspace: "证据工作区",
  canvasView: "查看内容",
  diff: "文件差异",
  retainedNodes: "共保留 {count} 条证据",
  displayedEvidenceNodes: "当前显示 {visible} / {total} 条证据",
  runtimeFilesChanged: "{count} 个 Skill 文件发生变更",
  actionCenterContext: "下一步：{action} · 由主 Agent 负责",
  enterDiffFocus: "进入差异专注模式",
  exitDiffFocus: "退出差异专注模式",
  focusOnDiff: "专注查看文件差异",
  exitFocus: "退出专注查看",
  immutableRunRecord: "可追溯评测记录",
  evidenceChain: "评测证据",
  evidenceChainDescription: "先看发布结论，再打开失败场景与未通过检查，最后阅读它实际使用的原始证据。",
  firstReviewGuide: "第一次 Review：发布结论 → 失败场景 → 未通过检查 → 原始证据",
  blockingEvidenceFlow: "当前阻塞：{cases} 个需处理场景 → {gates} 项未通过发布门禁",
  blockingEvidenceExplanation: "发布门禁由场景证据汇总；同一个阻塞问题可能作为“场景结论”和“门禁结论”各显示一次，但场景数只计一次。",
  evidenceTreeControls: "评测证据树控制",
  evidenceHierarchy: "评测证据树",
  expandAllEvidence: "全部展开",
  collapseAllEvidence: "全部收起",
  expandEvidence: "展开 {label}",
  collapseEvidence: "收起 {label}",
  statusLegend: "结论图例",
  passed: "通过",
  pending: "待确认",
  blocked: "阻塞",
  openEvidence: "打开证据 {label}",
  viewEvidenceDetails: "查看 {label} 的详情",
  viewDetails: "查看详情",
  childItems: "{count} 条下级证据",
  repeatMeta: "第 {count} 轮执行",
  retainedEvidenceRecord: "可追溯证据记录",
  loadingDiffRenderer: "正在准备文件差异视图…",
  noRuntimeChanges: "Skill 文件没有变化",
  candidateMatchesRuntime: "候选版与当前接受版本的运行内容一致。",
  evidenceInspector: "证据详情",
  inspector: "证据说明",
  retainedEvidenceDescription: "本次评测保留的原始证据，可用于复查和审计。",
  currentFinding: "当前结论",
  decisionBasis: "为什么是这个结果",
  nextReviewStep: "下一步怎么核对",
  viewBasisEvidence: "查看证据",
  whyItMatters: "为什么要看",
  evidenceInputs: "它读取了什么",
  reviewerChecklist: "人工 Review 应该看什么",
  automatedDecision: "自动检查如何判定",
  checkRule: "预设规则",
  observedResult: "实际观察",
  importance: "对结论的影响",
  sourceEvidence: "原始证据内容",
  sourceEvidenceDescription: "这是该检查实际读取、或该结论直接引用的保留内容。",
  loadingSourceEvidence: "正在读取保留证据…",
  sourceEvidenceUnavailable: "当前视图无法直接读取这份证据内容。",
  sourceEvidenceLoadFailed: "无法读取保留内容，或文件已不再匹配锁定摘要。",
  opaqueEvidence: "这是隐藏审计场景，内容不会在此公开，避免连续演进过程针对留出集调参。",
  binaryEvidence: "这是一份二进制证据，系统通过摘要校验，而不在页面中直接渲染。",
  oversizedEvidence: "该证据超过安全的页面内阅读上限；仍可在技术追溯信息中核对路径和摘要。",
  expandSourceContent: "展开全文",
  collapseSourceContent: "收起内容",
  contentTruncated: "页面只展示有界预览；完整文件仍由摘要锁定。",
  evidenceSize: "已保留 {size} 字节",
  evidenceId: "证据标识",
  arm: "对照版本",
  repeat: "执行轮次",
  assertion: "检查方式",
  artifactPath: "产物路径",
  decisionArtifact: "决策产物",
  technicalTrace: "技术追溯信息",
  technicalName: "内部名称",
  pairedArms: "候选版与旧版对照",
  missingObjectiveMetrics: "暂时无法判定，缺少客观指标：{metrics}",
  assertionsSummary: "必检项通过 {passed}/{total} · 通过率 {rate}",
  bindingSummary: "输入绑定错误 {binding} 项 · 禁止操作 {forbidden} 项 · 外部副作用 {effects} 项",
  semanticEvidence: "匿名语义评审",
  preference: "评审更偏好：{value}",
  unresolved: "尚无一致结论",
  provenance: "本次如何执行",
  subject: "被审查 Skill",
  subjectFingerprint: "被审查 Skill 指纹",
  baseline: "对照版本",
  baselineFingerprint: "对照版本指纹",
  plan: "评测计划指纹",
  profile: "执行配置指纹",
  target: "执行主体",
  harness: "分发方式",
  holdout: "场景可见性",
  controlAnchor: "演进状态锚点",
  none: "无",
  unknown: "未知",
  public: "公开可见",
  notUsed: "未使用",
  notRecorded: "未记录",
  selectEvidence: "请从中间的评测证据树中选择一条记录。",
  limitations: "当前限制",
  noLimitations: "当前没有已知限制。",
  refreshEvery: "每 {seconds} 秒自动刷新",
  generatedAt: "评测生成于 {time}",
  checkedAt: "检查时间 {time}",
  loadedAt: "上次刷新 {time}",
  attemptedAt: "上次尝试 {time}",
  generationTimeUnavailable: "未提供评测生成时间",
  notChecked: "尚未检查",
  pauseAutoRefresh: "暂停自动刷新",
  resumeAutoRefresh: "恢复自动刷新",
  refreshDashboard: "立即刷新 Dashboard",
  refreshing: "正在刷新评测证据",
  autoRefreshOn: "自动刷新已开启",
  autoRefreshPaused: "自动刷新已暂停",
  lastRefreshFailed: "最近一次刷新失败",
  retainedJsonArtifacts: "已保留 JSON 证据",
  evidenceDataLoaded: "评测数据已加载",
  connectingToEvidence: "正在连接评测证据",
  waitingForData: "正在等待评测结果数据…",
  evidenceUnavailable: "无法读取评测证据",
  retryConnection: "重新连接",
  retryHelp: "请确认只读 Dashboard 服务已启动，然后重新连接。",
  runMismatchTitle: "链接中的评测运行与当前数据不一致",
  runMismatchBody: "链接指向 {requested}；当前服务提供的是 {current}。",
  openCurrentRun: "查看当前评测运行",
  skipToEvidence: "跳转到证据工作区",
  copyEvidenceReference: "复制证据引用",
  evidenceReference: "Skill Reviewer 证据引用",
  semanticSummary: "证据含义",
  evidenceReferenceCopied: "证据引用已复制",
  evidenceReferenceCopyFailed: "无法复制证据引用",
  status: "结论状态",
  permalink: "直达链接",
  changedFiles: "变更文件",
  changedFileTree: "变更文件",
  changedFilesRoot: "SKILL-REVIEWER",
  expandChangedFilesRoot: "展开变更文件根目录",
  collapseChangedFilesRoot: "收起变更文件根目录",
  filterChangedFiles: "筛选变更文件",
  filterFiles: "筛选文件",
  changedRuntimeFiles: "本次变更的 Skill 文件",
  changedRuntimeFileTree: "本次变更的 Skill 文件目录",
  expandDirectory: "展开目录 {name}",
  collapseDirectory: "收起目录 {name}",
  directoryFileCount: "{count} 个文件",
  openDiff: "打开差异 {path}",
  noChangedFilesMatch: "没有变更文件匹配“{query}”。",
  documentDiff: "文档差异",
  noFileSelected: "未选择文件",
  fileNavigation: "文件导航",
  previousChangedFile: "上一个变更文件",
  previousFile: "上一个文件",
  nextChangedFile: "下一个变更文件",
  nextFile: "下一个文件",
  diffLayout: "差异布局",
  splitDiff: "左右对比",
  unifiedDiff: "合并对比",
  wrapLines: "自动换行",
  wrapLongLines: "长行自动换行",
  chooseChangedFile: "选择一个变更文件进行检查。",
  previewUnavailable: "当前文件无法预览",
  sizeSummary: "修改前 {oldSize} · 修改后 {newSize}",
  loadingPreview: "正在加载受限预览…",
  diffRenderFailed: "无法渲染差异",
  diffIntegrityFailed: "差异完整性校验失败",
  retryDiffPreview: "重试预览",
  copyDiagnostics: "复制诊断信息",
  diagnosticsCopied: "诊断信息已复制",
  diagnosticsCopyFailed: "无法复制诊断信息",
  lineSummary: "{oldLines} → {newLines} 行",
  actionCenter: "行动中心",
  humanDecisionHandoff: "基于证据的决策交接",
  actionCenterDescription: "先判断候选能否接受，再明确阻塞归属，最后只为主 Agent 创建一条可审计任务。",
  currentStateAndNextAction: "当前状态与状态机下一步",
  currentState: "当前状态",
  stateMachineNextAction: "状态机下一步",
  nextActionStop: "停止连续演进",
  nextActionReviewEvidence: "人工复核当前证据",
  leadAgentOwner: "由主 Agent 负责执行",
  candidateAcceptability: "这个候选可以接受吗？",
  candidateAcceptabilityDescription: "发布选拔必须同时满足三项条件；任一项不满足，候选都不能被接受。",
  criterion_hard_gates: "硬门禁",
  criterion_hard_gates_description: "必需断言、成对证据和执行安全检查必须全部通过。",
  criterion_pareto: "Pareto 不退化",
  criterion_pareto_description: "所有已声明目标都不能超过容忍阈值发生退化。",
  criterion_material_improvement: "实质提升",
  criterion_material_improvement_description: "至少一个主要目标必须达到预先声明的最小提升幅度。",
  awaitingEvidence: "等待证据",
  candidateVerdict: "候选判定",
  allAcceptanceConditionsMet: "三项发布选拔条件均已满足。",
  acceptanceConditionsNotMet: "至少一项必需的发布选拔条件尚未满足。",
  acceptancePendingEvidence: "保留证据还不足以作出候选判定。",
  failureAttribution: "阻塞应该由谁处理？",
  primaryAttributionSummary: "主要归因：{owner}",
  noFailureAttributed: "当前没有可归因的失败。",
  attribution_skill: "Skill 行为",
  attribution_skill_description: "候选 Skill 的指令或实际行为未满足必需结果、安全约束或目标。",
  attribution_eval: "Eval 设计",
  attribution_eval_description: "场景、指标或断言契约本身无法支撑预期判定。",
  attribution_execution_environment: "执行环境",
  attribution_execution_environment_description: "输入绑定、执行器或运行环境使本次执行不可被信任。",
  attribution_evidence: "证据缺失",
  attribution_evidence_description: "候选版或对照版的必需产物缺失、不完整。",
  attribution_human: "人工裁决",
  attribution_human_description: "自动验证链已到达必须由人授权或确认的边界。",
  attributionStatus_primary: "主要阻塞",
  attributionStatus_contributing: "共同影响",
  attributionStatus_clear: "未发现问题",
  attributionStatus_waiting: "等待人工决定",
  noAttributionSignal: "保留证据中没有发现对应信号。",
  openAttributionEvidence: "打开归因证据",
  signal_binding_error: "执行输入与已锁定计划不一致。",
  signal_candidate_evidence_incomplete: "候选版产物不完整。",
  signal_required_assertion_failed: "候选版有必需检查未通过。",
  signal_unsafe_behavior_observed: "发现禁止操作或外部副作用。",
  signal_objective_regressed: "候选版在已声明目标上发生退化。",
  signal_stochastic_direction_disagreement: "多次随机执行对结果方向存在分歧。",
  signal_objective_metric_unavailable: "成对证据中缺少目标指标。",
  signal_baseline_evidence_incomplete: "对照版本的证据不完整。",
  signal_pareto_regression: "候选版未满足 Pareto 不退化。",
  signal_material_improvement_missing: "主要目标没有达到实质提升。",
  signal_objective_evidence_missing: "本次没有生成可用的目标证据。",
  signal_declared_metric_missing: "Eval 契约要求的指标缺失。",
  signal_paired_evidence_missing: "必需的成对对照证据缺失。",
  signal_audit_authorization_required: "一次性安全审计需要人工授权。",
  signal_release_confirmation_required: "安全审计通过后仍需人工确认发布。",
  unknownAttributionSignal: "系统记录了其他信号，请在技术追溯信息中核对。",
  recommendedActions: "推荐动作",
  recommendedActionsDescription: "动作可用性由状态机决定；按钮只创建任务，不执行操作，也不改变证据。",
  action_generate_candidate: "生成下一候选",
  action_generate_candidate_description: "请主 Agent 结合失败证据和候选谱系，提出下一版 Skill 候选。",
  action_rerun_execution: "执行或重跑已授权场景",
  action_rerun_execution_description: "请主 Agent 分发已经授权的计划，并保留新一轮真实执行产物。",
  action_propose_eval_change: "提交 Eval 修改建议",
  action_propose_eval_change_description: "只生成可评审建议；真正修改不可变 Eval 仍需用户明确确认并重新锁定。",
  action_authorize_audit: "请求安全审计授权",
  action_authorize_audit_description: "创建一次性隐藏审计的人工决策任务；该任务本身不会授予权限。",
  action_request_release_confirmation: "请求发布确认",
  action_request_release_confirmation_description: "安全审计通过后，创建最终的人工发布确认任务。",
  recommended: "当前推荐",
  humanConfirmationBoundary: "仍须人工明确确认；创建任务本身不会越过此边界。",
  creatingTask: "正在创建任务…",
  createLeadAgentTask: "交给主 Agent",
  notAvailableInCurrentState: "当前状态不可用",
  actionTaskCreateFailed: "任务未创建。运行状态可能已推进，请刷新后重新核对当前状态。",
  taskAuditTrail: "行动任务审计记录",
  refreshTaskAudit: "刷新",
  loadingTaskAudit: "正在读取独立任务账本…",
  taskAuditUnavailable: "任务账本暂不可用；评测证据仍可读取且未被改变。",
  noActionTasks: "本次运行尚未请求任何行动任务。",
  taskOwnedByLeadAgent: "由主 Agent 负责",
  taskRequested: "已请求",
  nextActionComesFromStateMachine: "该值直接投影自已验证的演进状态，不是 Dashboard 临时猜测。",
  executionOwner: "执行责任",
  leadAgentOwnerDescription: "Dashboard 只记录意图。主 Agent 会重新校验前置状态、按需分发执行者，并保留新的验证证据。",
  whenCreatingTask: "点击后会发生什么",
  taskStepSnapshot: "把请求绑定到本次运行和当前 Dashboard 摘要。",
  taskStepPrecondition: "要求状态机 next_action 仍与请求一致。",
  taskStepAudit: "在证据工作区之外追加一条摘要链任务记录。",
  taskStepAgent: "由主 Agent 消费任务，浏览器不会直接执行任何工作。",
  controlBoundary: "控制边界",
  evidenceRemainsReadOnly: "运行证据保持只读",
  evidenceRemainsReadOnlyDescription: "行动请求不能修改计划、产物、判定或 Dashboard 投影。",
  evalRemainsImmutable: "evals.json 保持不可变",
  evalRemainsImmutableDescription: "Eval 动作只提出建议；后续修改必须由用户确认。",
  rootDirectory: "Skill 根目录",
};

const messages: Record<Locale, Record<MessageKey, string>> = {
  en: englishMessages,
  "zh-CN": chineseMessages,
};

const statusLabels: Record<string, string> = {
  passed: "通过",
  accepted: "候选已保留",
  "audit-passed": "安全审计通过",
  retained: "证据已保留",
  "regression-verified": "已完成新旧版对照验证",
  "behavior-verified": "已完成真实行为验证",
  failed: "未通过",
  rejected: "候选已淘汰",
  regressed: "质量发生退化",
  "audit-failed": "安全审计未通过",
  invalid: "评测数据无效",
  stale: "证据已过期",
  disagreement: "评审存在分歧",
  blocked: "已阻塞",
  pending: "待确认",
  "awaiting-audit": "等待安全审计",
  inconclusive: "证据不足",
  incomplete: "证据不完整",
  missing: "证据缺失",
  "no-change": "无有效改进",
  exhausted: "已用完演进轮次",
  completed: "评测已完成",
  optimizing: "持续优化中",
  agreement: "评审结论一致",
};

const valueLabels: Record<string, string> = {
  development: "开发验证",
  selection: "发布选拔",
  audit: "安全审计",
  public: "公开可见",
  opaque: "隐藏评测",
  "public-calibration": "公开校准场景",
  "opaque-holdout": "隐藏评测场景",
  old_skill: "旧版 Skill",
  with_skill: "候选版 Skill",
  candidate: "候选版 Skill",
  without_skill: "未使用 Skill",
  baseline: "对照版本",
  "native-agent": "由主 Agent 直接执行",
  "lead-agent-dispatch": "由主 Agent 负责分发",
  "trusted-orchestrator": "由可信编排器隔离执行",
  "orchestrator-default": "遵循编排器默认采样策略",
  "local/trusted": "本地可信存储",
  file_exists: "检查必需文件是否存在",
  text_contains: "检查必需信息是否完整",
  text_matches: "检查结论表达是否符合要求",
  text_not_contains: "检查是否出现无依据结论",
  semantic_pair: "匿名比较候选版与旧版",
  continue: "延续上一轮",
  reset: "重新开始",
  propose_candidate: "生成下一候选",
  run_authorized_selection: "执行已授权的发布选拔",
  run_authorized_audit: "执行已授权的安全审计",
  authorize_audit: "等待安全审计授权",
  request_user_release: "请求人工发布确认",
  review_evidence: "人工复核当前证据",
  stop: "停止连续演进",
  lead_agent: "主 Agent",
  added: "新增",
  removed: "删除",
  modified: "修改",
  run: "评测运行",
  gate: "发布门禁",
  iteration: "演进轮次",
  case: "评测场景",
  assertion: "检查项",
  artifact: "证据文件",
};

export function translate(
  locale: Locale,
  key: MessageKey,
  values: MessageValues = {},
): string {
  return messages[locale][key].replace(/\{(\w+)\}/g, (_, name: string) =>
    String(values[name] ?? `{${name}}`),
  );
}

export function localizeStatus(locale: Locale, status: string): string {
  return locale === "zh-CN" ? (statusLabels[status] ?? status) : status;
}

export function localizeValue(locale: Locale, value: string): string {
  return locale === "zh-CN" ? (valueLabels[value] ?? value) : value;
}

interface UiPreferences {
  locale: Locale;
  theme: Theme;
  setLocale: (locale: Locale) => void;
  setTheme: (theme: Theme) => void;
  t: (key: MessageKey, values?: MessageValues) => string;
}

const UiPreferencesContext = createContext<UiPreferences | null>(null);

function readStoredPreference<T extends string>(
  key: string,
  allowed: readonly T[],
): T | null {
  try {
    const value = window.localStorage.getItem(key);
    return allowed.includes(value as T) ? (value as T) : null;
  } catch {
    return null;
  }
}

function initialLocale(): Locale {
  return (
    readStoredPreference(preferenceStorageKeys.locale, ["en", "zh-CN"]) ??
    (window.navigator.language.toLowerCase().startsWith("zh") ? "zh-CN" : "en")
  );
}

function initialTheme(): Theme {
  return (
    readStoredPreference(preferenceStorageKeys.theme, ["light", "dark"]) ??
    (window.matchMedia?.("(prefers-color-scheme: dark)").matches ? "dark" : "light")
  );
}

export function UiPreferencesProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(initialLocale);
  const [theme, setTheme] = useState<Theme>(initialTheme);

  useLayoutEffect(() => {
    document.title = translate(locale, "pageTitle");
    document.documentElement.lang = locale;
    document.documentElement.dataset.theme = theme;
    document.documentElement.style.colorScheme = theme;
    try {
      window.localStorage.setItem(preferenceStorageKeys.locale, locale);
      window.localStorage.setItem(preferenceStorageKeys.theme, theme);
    } catch {
      // Preferences remain valid for the current session when storage is unavailable.
    }
  }, [locale, theme]);

  useEffect(() => {
    const syncPreference = (event: StorageEvent) => {
      if (event.key === preferenceStorageKeys.locale && ["en", "zh-CN"].includes(event.newValue ?? "")) {
        setLocale(event.newValue as Locale);
      }
      if (event.key === preferenceStorageKeys.theme && ["light", "dark"].includes(event.newValue ?? "")) {
        setTheme(event.newValue as Theme);
      }
    };
    window.addEventListener("storage", syncPreference);
    return () => window.removeEventListener("storage", syncPreference);
  }, []);

  const value = useMemo<UiPreferences>(
    () => ({
      locale,
      theme,
      setLocale,
      setTheme,
      t: (key, values) => translate(locale, key, values),
    }),
    [locale, theme],
  );

  return (
    <UiPreferencesContext.Provider value={value}>
      {children}
    </UiPreferencesContext.Provider>
  );
}

export function useUiPreferences(): UiPreferences {
  const preferences = useContext(UiPreferencesContext);
  if (!preferences) {
    throw new Error("useUiPreferences must be used inside UiPreferencesProvider");
  }
  return preferences;
}
