import {
  createContext,
  useContext,
  useEffect,
  useLayoutEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

export type Locale = "en" | "zh-CN";
export type Theme = "light" | "dark";
export const fontScaleOptions = [0.9, 1, 1.1, 1.25, 1.4, 1.6] as const;
export type FontScale = (typeof fontScaleOptions)[number];

export const preferenceStorageKeys = {
  locale: "skill-reviewer.locale",
  theme: "skill-reviewer.theme",
  fontScale: "skill-reviewer.font-scale",
} as const;

const englishMessages = {
  pageTitle: "Skill Reviewer · Decision Review",
  appTitle: "Skill Reviewer decision review",
  brandEvidence: "Decision review",
  displayPreferences: "Display preferences",
  language: "Language",
  switchToEnglish: "Switch to English",
  switchToChinese: "Switch to Simplified Chinese",
  switchToDarkTheme: "Switch to dark theme",
  switchToLightTheme: "Switch to light theme",
  darkTheme: "Dark",
  lightTheme: "Light",
  textSize: "Text size",
  decreaseTextSize: "Decrease text size",
  increaseTextSize: "Increase text size",
  resetTextSize: "Reset text size to 100%",
  textSizeValue: "Text size {percent}%",
  openCommandPalette: "Go to evidence",
  commandPaletteTitle: "Go to evidence",
  commandPalettePlaceholder: "Search cases, evidence, files, and commands",
  closeCommandPalette: "Close command palette",
  commandsAvailable: "Available commands",
  noCommandsFound: "No matching destination",
  noCommandsHint: "Try a case ID, evidence label, file path, or action.",
  navigate: "navigate",
  runCommand: "open",
  close: "close",
  actionGroup: "Action",
  caseGroup: "Case",
  evidenceGroup: "Evidence",
  fileGroup: "File",
  copyViewLink: "Copy view link",
  downloadEvidenceJson: "Download projection JSON",
  viewLinkCopied: "View link copied",
  viewLinkCopyFailed: "View link could not be copied",
  evidenceJsonDownloaded: "Projection JSON download started",
  evidenceJsonDownloadFailed: "Projection JSON could not be downloaded",
  showEvidence: "Show evidence chain",
  showExecutionTrace: "Show Agent execution records",
  showDiff: "Show document diff",
  showAttention: "Show cases needing attention",
  showAllCases: "Show all cases",
  useDarkTheme: "Use dark theme",
  useLightTheme: "Use light theme",
  useChinese: "Use Simplified Chinese",
  useEnglish: "Use English",
  resizeCasePane: "Resize evaluation scenarios",
  resizeInspectorPane: "Resize evidence inspector",
  resizePaneHint: "Drag to resize · use arrow keys to adjust · press Enter to reset",
  resetPaneWidths: "Reset pane widths",
  resetPaneWidthsDescription: "Restore the scenario rail and evidence inspector to their default widths.",
  paneWidthsReset: "Pane widths reset",
  live: "Connected",
  connecting: "Connecting",
  stale: "Stale",
  readOnly: "evidence read-only",
  releaseReady: "Ready for release",
  hardGates: "Hard gates",
  casesPassed: "Cases passed",
  round: "Round",
  evidence: "Evidence",
  evidenceScope: "Evidence scope",
  runOverview: "Run overview",
  evaluationSuite: "Evaluation suite",
  cases: "Cases",
  split: "Split",
  evaluationLifecycle: "Evaluation lifecycle",
  singleScenarioStageLabel: "Single scenario · {stage}",
  evolutionDetails: "Evolution details",
  allStageCases: "All cases",
  allStageFilterOption: "All evaluation stages; {count} cases",
  stageFilterOption: "{stage}; {count} cases",
  stagePurpose: "What this stage does",
  stageOutcome: "Result",
  allStagesTitle: "See the complete evaluation path",
  allStagesDescription: "This combines development validation, candidate selection, and release audit for browsing. All cases is a view, not a fourth stage.",
  allStagesOutcome: "A cross-stage overview only; it does not create another evaluation decision.",
  developmentStageShort: "Find issues",
  developmentStageTitle: "Find problems cheaply before a full comparison",
  developmentStageDescription: "Run only the relevant cases while iterating. The resulting evidence may guide the optimizer and the next candidate.",
  developmentStageOutcome: "Diagnostic signal only; it cannot approve a candidate or a release.",
  selectionStageShort: "Compare versions",
  selectionStageTitle: "Choose a candidate against the accepted baseline",
  selectionStageDescription: "Run the complete frozen selection set and require every hard gate, objective non-regression, and repeat-consistent material improvement.",
  selectionStageOutcome: "Pass advances to one release audit; otherwise the Agent proposes another candidate, up to three rounds.",
  auditStageShort: "Final holdout",
  auditStageTitle: "Check generalization once without teaching the optimizer",
  auditStageDescription: "After selection passes, run the complete audit set once. Its cases and results are never fed back into another candidate.",
  auditStageOutcome: "Pass makes the behavioral evidence release-eligible; a person still confirms the external release.",
  publicAuditScope: "This run uses public calibration evidence. It tests audit behavior but cannot authorize release by itself.",
  opaqueAuditScope: "This run uses an external opaque holdout and can support the one-shot release audit.",
  searchCases: "Search cases",
  filterCases: "Filter cases",
  caseStatus: "Scenario result",
  attention: "Needs attention",
  caseFilterOption: "{label}; matching scenario count: {count}",
  caseFilterScope: "This filter counts evaluation scenarios only; release gates are listed separately in the evidence tree.",
  noCasesMatch: "No cases match this view.",
  clearFilters: "Clear filters",
  caseResults: "{count} of {total} cases",
  all: "All",
  development: "Development validation",
  selection: "Candidate selection",
  audit: "Release audit",
  pairedRuns: "{count}× paired",
  noCasesInSplit: "No cases in this split.",
  evolution: "Evolution",
  continuitySummary: "continuity epoch {epoch} · {count} rejected",
  candidateLineage: "Candidate lineage",
  lineageRound: "Round {round}",
  evidenceWorkspace: "Evidence workspace",
  canvasView: "Canvas view",
  reviewTab: "Review",
  changesTab: "Changes",
  runsTab: "Runs",
  auditTab: "Evidence archive",
  executionTrace: "Agent trace",
  executionTraceContext: "{observed}/{expected} Agent executions retained",
  executionTraceKicker: "eval case → real Agent events",
  executionTraceTitle: "Agent execution records",
  executionTraceDescription: "Choose an eval case, compare candidate and declared comparison runs, then inspect the files, tools, commands, messages, errors, and outputs that were actually recorded.",
  traceAttentionSummary: "Trace attention summary",
  traceAttentionTitle: "Review anomalies first",
  traceAttentionDescription: "Failures outrank evidence gaps, then candidate/comparison differences and unusually slow executions.",
  traceFailures: "Failures",
  traceFailureBreakdown: "{checks} checks · {events} events",
  traceEvidenceGaps: "Evidence gaps",
  traceComparisonDifferences: "Candidate/comparison differences",
  traceSlowExecutions: "Slow executions",
  traceSlowThreshold: "threshold {duration}",
  traceTechnicalContext: "Technical provenance and execution boundaries",
  observableEvidenceBoundary: "Observable Agent events only",
  observableEvidenceBoundaryDescription: "This view never derives a fake trace from status summaries and never exposes private chain-of-thought. If the harness did not capture an event, it remains visibly missing.",
  localUnattestedTrace: "Local full access is not an isolation guarantee",
  localUnattestedTraceDescription: "A local Agent process ran with observable event capture, but it could access resources beyond the repeat workspace. Use this trace to inspect behavior; do not treat it as proof that OS permissions or network denial were enforced.",
  selectTraceCase: "Choose an evaluation scenario",
  traceCaseIndexTitle: "Eval case run index",
  traceCaseIndexDescription: "Each row is one eval case. Trace coverage counts the planned candidate/comparison repeats that retained a real Agent event stream.",
  traceCaseColumn: "Eval case",
  traceStageColumn: "Stage",
  tracePolicyColumn: "Run policy",
  traceCoverageColumn: "Real traces",
  traceDurationColumn: "Duration",
  traceStatusColumn: "Result",
  deterministicRunPolicy: "1 repeat per arm",
  stochasticRunPolicy: "{count} repeats per arm",
  capturedAgentTraces: "Real traces captured",
  selectedEvalCase: "Selected eval case",
  traceResponsibilityTitle: "Who does what in this record",
  leadAgentRole: "Lead Agent",
  leadDispatchesWorker: "Lead Agent dispatches; the Eval worker executes",
  leadAgentTraceBoundary: "Uses Skill Reviewer to lock the plan and dispatch each case/arm/repeat cell. Its governance decisions stay in retained run artifacts; they are not scored as evaluated behavior.",
  evalWorkerRole: "Eval worker",
  nativeSubagent: "Host-observed native subagent",
  localAgentProcess: "Process-observed local Agent",
  declaredAgentProfile: "Declared executor profile",
  externalAgentHarness: "External Agent harness",
  executorNotRecorded: "Eval executor not recorded",
  evalWorkerTraceBoundary: "This is the evaluated actor. The candidate arm follows the frozen candidate Skill; the comparison arm follows its declared old-Skill or without-Skill condition. Observable actions form the real Trace.",
  declaredExecutorBoundary: "The run declares this executor profile, but no valid Agent or harness dispatch receipt binds the selected execution. Treat the identity as configuration, not proof that this Agent actually ran.",
  dispatchReceipt: "Dispatch receipt",
  sourceTrace: "Source event stream",
  sourceAgent: "Source Agent",
  adapterProvenance: "Adapter provenance",
  dispatchReceiptMissing: "Executor identity is not dispatch-bound",
  dispatchReceiptMissingDescription: "A profile describes the intended executor. A valid dispatch receipt is required before this view identifies a native subagent or local Agent process.",
  nestedAgentTraceCaptured: "Nested Agent events are declared capturable",
  nestedAgentTraceNotCaptured: "Nested Agent behavior is not declared in this Trace",
  nestedAgentTraceBoundary: "If the evaluated Skill starts another Agent, only harness-captured child events may be shown; missing child activity is never inferred.",
  selectRepeat: "Choose a repeat",
  executionMatrixTitle: "Execution matrix",
  executionMatrixDescription: "Rows are independent repeats; columns are isolated experiment arms. Select one retained cell to inspect its real Trace.",
  repeatColumn: "Repeat",
  repeatNotEvolutionRound: "Repeat {repeat} is an independent execution of the same locked case—not an evolution round.",
  executionMissing: "Execution missing",
  traceCaptured: "Trace captured",
  traceNotCaptured: "Trace missing",
  executionCellLabel: "{arm} · Repeat {repeat} · {status}",
  assertionScore: "Checks {passed}/{total}",
  eventTimeline: "Observable event timeline",
  eventTimelineDescription: "Events appear in capture order. Open one to inspect the exact observable payload and artifact references.",
  realTraceMissing: "No real Agent trace was captured",
  realTraceMissingDescription: "An execution summary is not a trace. Rerun this eval case with harness-native or lead-Agent observable event capture enabled.",
  captureSource: "Capture source",
  capturedEvents: "Events",
  duration: "Duration",
  traceDigest: "Trace digest",
  eventSequence: "Event {sequence}",
  noEventDetails: "This event has no additional observable payload.",
  artifactReferences: "Referenced artifacts",
  checksAndJudge: "Checks and judge results",
  checksAndJudgeDescription: "After reading the actual run, verify how deterministic checks and the semantic judge used its retained artifacts.",
  linkedTraceEvents: "{count} linked Trace events",
  locateTraceEvent: "Locate Trace",
  semanticJudgeResults: "Blind semantic judge",
  semanticJudgeResultsDescription: "The judgment remains bound to exact output digests and the Trace events that produced them.",
  judgePreference: "Preference",
  noCheckComparison: "No paired check result was retained for this case.",
  lockedEvalDefinition: "Locked eval bindings",
  manifestDigest: "evals.json digest",
  planDigest: "locked plan digest",
  determinism: "Execution policy",
  deterministicAssertions: "Deterministic checks",
  semanticAssertions: "Semantic checks",
  failedChecks: "Failed checks",
  candidateLane: "Candidate under review",
  baselineLane: "Comparison condition",
  comparisonConclusion: "Comparison",
  comparison_candidate_improved: "Candidate passes; comparison fails",
  comparison_candidate_regressed: "Candidate fails; comparison passes",
  comparison_both_passed: "Both arms pass",
  comparison_both_failed: "Both arms fail",
  comparison_mixed: "Repeat results disagree",
  comparison_incomplete: "One arm is missing evidence",
  comparison_unpaired: "No paired comparison available",
  repeatObservation: "Repeat {repeat}",
  missingArmObservation: "No retained observation for this arm",
  armEvidenceGroup: "Version evidence comparison",
  candidateEvidenceDescription: "Candidate executions, checks, and artifacts are shown on the left.",
  baselineEvidenceDescription: "Comparison-condition executions, checks, and artifacts are shown on the right.",
  armEvidenceSummary: "{passed}/{total} checks passed · {artifacts} artifacts",
  pairedEvidenceRegion: "Paired candidate and comparison evidence",
  pairedEvidenceLayoutDescription: "Each row aligns the same check or artifact so result differences are visible without scrolling between sections.",
  pairedEvidenceItems: "{count} aligned items",
  itemByItemComparison: "item by item",
  evidenceComparisonSame: "Same result",
  evidenceComparisonDifferent: "Different result",
  evidenceComparisonMissing: "Evidence missing",
  candidateEvidenceMissing: "No matching candidate evidence was retained.",
  baselineEvidenceMissing: "No matching comparison evidence was retained.",
  diff: "Diff",
  diffEvidenceMissing: "Diff · evidence missing",
  displayedEvidenceNodes: "Showing {visible} of {total} evidence nodes",
  runtimeFilesChanged: "{count} runtime files changed",
  enterDiffFocus: "Enter diff focus mode",
  exitDiffFocus: "Exit diff focus mode",
  focusOnDiff: "Focus on diff",
  exitFocus: "Exit focus mode",
  immutableRunRecord: "Immutable run record",
  evidenceChainDescription: "Start with the release decision, open a failed scenario, inspect its failed check, then read the source evidence.",
  reviewOverview: "Review overview",
  problemsToFix: "Problems to fix",
  primaryBlockerLabel: "Primary blocker",
  openValidityStepEvidence: "Open the evidence behind {step}",
  openObjectiveCaseEvidence: "Open the evidence for {title}",
  verificationLevelLabel: "evidence",
  runStateLabel: "run state",
  releaseBlockerCount: "Independent issues to address: {count}",
  releaseBlockerNone: "No release blocker is present in the retained evidence.",
  noKnownBlockerEvidenceIncomplete:
    "No known blocker was found, but release evidence is incomplete",
  evidenceIncompleteReleaseBlocked:
    "Release is not ready. Complete the required release evidence before making a decision.",
  notConfigured: "Not configured",
  criterionFailedSummary: "{passed}/{total} checks satisfied; this condition failed.",
  criterionEvidenceUnavailable: "No bounded supporting evidence was retained for this condition.",
  issueWhy: "Why this failed",
  issueNextStep: "What to do next",
  issueAction_skill: "Fix the Skill behavior, then run this scenario again.",
  issueAction_eval: "Submit an eval change proposal for human review.",
  issueAction_execution_environment: "Repair the execution setup or input binding, then rerun.",
  issueAction_evidence: "Restore the missing candidate or baseline evidence, then rerun.",
  issueAction_human: "Ask the reviewer to authorize or confirm the pending boundary.",
  issueEvidenceCount: "{count} retained evidence items can be checked.",
  issueEvidenceSummary: "{checks} failed checks · {sources} source artifacts",
  scenarioDidNotPass: "The evaluation scenario did not pass",
  openProblemEvidence: "Review the evidence for this problem",
  readyForHumanConfirmation: "No automatic blocker remains; a person still owns the release decision.",
  automaticNoBlockerSummary: "No known blocker remains, but release evidence is incomplete and release is not ready. The lead Agent continues to the next locked evaluation stage automatically.",
  noFailedCheckRecorded: "No failed candidate check was retained; inspect the scenario or gate evidence for missing or inconclusive inputs.",
  decisionCoverage: "Decision coverage",
  decisionEvidence: "Decision evidence",
  whatChanged: "What changed",
  changeEvidenceCount: "{count} changed files captured",
  noChangeEvidenceCaptured: "No change evidence captured",
  evidenceCoverage: "Evidence coverage",
  evidenceCoverageRatio: "{captured}/{expected} executions verified",
  decisionValidity: "Decision validity",
  decisionValidityDescription: "Trust the evidence, then the measurement, before judging the Skill.",
  evidenceIntegrity: "Evidence integrity",
  evidenceIntegrityValid: "Bindings and traces verified",
  evidenceIntegrityInvalid: "Evidence integrity failed",
  measurementValidity: "Measurement validity",
  measurementValid: "Judging rules + sampling verified",
  measurementInvalid: "Measurement invalid",
  measurementUnverified: "Measurement unverified",
  measurementPending: "Preflight pending",
  candidateQuality: "Candidate quality",
  candidateAccepted: "Accepted by selection",
  candidateRejected: "Candidate not accepted",
  candidatePending: "Candidate decision pending",
  candidateNotJudged: "Skill not judged",
  objectiveEvidence: "Objective comparison",
  objectiveEvidenceTitle: "What changed in measured behavior",
  objectiveEvidenceDescription: "Direction-normalized deltas compare each paired repeat with the accepted baseline. Positive favors the candidate; these repeats show consistency, not statistical confidence.",
  objectiveMeanDelta: "Mean Δ",
  objectiveBaselineValue: "Baseline value",
  objectiveCandidateValue: "Candidate value",
  objectivePairedDeltas: "Paired-repeat Δ",
  objectiveRepeatCount: "n = {count}",
  objectiveGuardrails: "Predeclared guardrails",
  objectiveGuardrailValues: "non-regression ≥ {tolerance} · material ≥ {material}",
  objectiveRegressionObserved: "Regression observed",
  objectiveMaterialEveryRepeat: "Material gain in every paired repeat",
  objectiveNonRegressedOnly: "No regression; material gain is not repeat-consistent",
  noKnownRisk: "No known release risk",
  evidenceIncomplete: "Release evidence is incomplete",
  reviewChangeEvidence: "Review change evidence",
  reviewExecutionEvidence: "Review execution evidence",
  reviewPrimaryRiskEvidence: "Review primary risk evidence",
  recommendedNextStep: "Recommended next step",
  auditArchive: "Complete audit record",
  auditArchiveDescription: "Technical evidence index for reproduction and audit. It is intentionally secondary to the review decision.",
  evidenceTreeControls: "Evidence hierarchy controls",
  evidenceHierarchy: "Evidence hierarchy",
  expandAllEvidence: "Expand all",
  collapseAllEvidence: "Collapse all",
  expandEvidence: "Expand {label}",
  collapseEvidence: "Collapse {label}",
  statusLegend: "Status legend",
  passed: "Passed",
  pending: "Pending",
  blocked: "Blocked",
  openEvidence: "Open evidence {label}",
  childItems: "{count} items",
  repeatMeta: "repeat {count}",
  loadingDiffRenderer: "Loading diff renderer…",
  noRuntimeChanges: "No change evidence captured",
  candidateMatchesRuntime: "The projection contains no change artifact. This is an evidence gap, not proof that nothing changed.",
  evidenceInspector: "Evidence inspector",
  inspector: "Review guide",
  retainedEvidenceDescription: "Retained evidence from the immutable run workspace.",
  currentFinding: "Current finding",
  decisionBasis: "Why this result",
  nextReviewStep: "Next review step",
  viewBasisEvidence: "View evidence",
  whyItMatters: "Why this exists",
  evidenceInputs: "What it reads",
  reviewerChecklist: "What a human should verify",
  importance: "Decision impact",
  sourceEvidence: "Source evidence",
  sourceEvidenceDescription: "The exact retained content read by this check or cited by this decision.",
  loadingSourceEvidence: "Loading retained evidence…",
  sourceEvidenceUnavailable: "Source content is not available in this view.",
  sourceEvidenceLoadFailed: "The retained content could not be loaded or no longer matches its bound digest.",
  opaqueEvidence: "Content is hidden because this is an opaque audit scenario. The boundary prevents the evolution loop from tuning against holdout evidence.",
  binaryEvidence: "This retained artifact is binary and is verified by digest instead of being rendered.",
  oversizedEvidence: "This retained artifact is larger than the safe inline-reader limit. Its digest and path remain available in technical trace.",
  evidencePreview: "Evidence preview",
  evidenceViewMode: "Evidence view mode",
  structuredPreview: "Structure",
  renderedPreview: "Rendered",
  sourceView: "Source",
  jsonLineRecords: "JSONL records",
  jsonRoot: "JSON document",
  jsonLinesFormat: "JSON Lines",
  plainTextFormat: "Plain text",
  markdownImageNotLoaded: "Image not loaded: {alt}",
  unnamedImage: "unnamed image",
  closeEvidencePreview: "Close evidence preview",
  evidenceDigestBound: "Content verified against its retained digest.",
  evidencePreviewHint: "Open the reading view for the complete, scrollable evidence.",
  openFullPreview: "Open full preview",
  contentTruncated: "Preview truncated at the bounded reader limit; the full file remains bound by digest.",
  evidenceSize: "{size} retained bytes",
  evidenceId: "Evidence ID",
  arm: "Arm",
  repeat: "Repeat",
  assertion: "Assertion",
  artifactPath: "Artifact path",
  decisionArtifact: "Decision artifact",
  technicalTrace: "Technical trace",
  technicalName: "Internal name",
  pairedArms: "Paired arms",
  missingObjectiveMetrics: "Missing objective metrics: {metrics}",
  assertionsSummary: "{passed}/{total} assertions · {rate}",
  bindingSummary: "{binding} binding · {forbidden} forbidden · {effects} side effects",
  semanticEvidence: "Semantic evidence",
  preference: "preference {value}",
  unresolved: "unresolved",
  provenance: "Execution context",
  subject: "Subject",
  subjectFingerprint: "Reviewed Skill fingerprint",
  baseline: "Baseline",
  baselineFingerprint: "Baseline fingerprint",
  plan: "Plan",
  profile: "Profile",
  target: "Target",
  harness: "Harness",
  holdout: "Holdout",
  controlAnchor: "Control anchor",
  none: "none",
  unknown: "unknown",
  public: "public",
  notUsed: "not used",
  notRecorded: "not recorded",
  selectEvidence: "Select an evidence record.",
  limitations: "Limitations",
  noLimitations: "No recorded limitations.",
  refreshEvery: "every {seconds}s",
  generatedAt: "Generated {time}",
  loadedAt: "Loaded {time}",
  attemptedAt: "Attempted {time}",
  notChecked: "Not checked yet",
  pauseAutoRefresh: "Pause automatic refresh",
  resumeAutoRefresh: "Resume automatic refresh",
  refreshDashboard: "Refresh dashboard now",
  autoRefreshOn: "Checking for projection updates",
  autoRefreshPaused: "Auto-refresh paused",
  lastRefreshFailed: "Last refresh failed",
  connectingToEvidence: "Connecting to evidence",
  waitingForData: "Waiting for dashboard-data.json…",
  dashboardDataIncompatible: "Dashboard data is incompatible",
  dashboardDataRegenerateHelp:
    "Regenerate dashboard-data.json with the current skill-reviewer runtime, then refresh this page.",
  dashboardRenderFailed: "Dashboard could not render this projection",
  dashboardRenderRecovery:
    "Regenerate dashboard-data.json with the current skill-reviewer runtime, then reload this page.",
  reloadDashboard: "Reload dashboard",
  evidenceUnavailable: "Evidence is unavailable",
  retryConnection: "Retry connection",
  retryHelp: "Check that the read-only dashboard server is running, then retry.",
  skipToEvidence: "Skip to evidence workspace",
  copyEvidenceReference: "Copy evidence reference",
  evidenceReference: "Skill Reviewer evidence reference",
  semanticSummary: "Meaning",
  evidenceReferenceCopied: "Evidence reference copied",
  evidenceReferenceCopyFailed: "Evidence reference could not be copied",
  status: "Status",
  permalink: "Permalink",
  changedFileTree: "Changed files",
  changedFilesRoot: "SKILL-REVIEWER",
  expandChangedFilesRoot: "Expand changed file root",
  collapseChangedFilesRoot: "Collapse changed file root",
  filterChangedFiles: "Filter changed files",
  filterFiles: "Filter files",
  changedRuntimeFileTree: "Changed runtime file tree",
  expandDirectory: "Expand directory {name}",
  collapseDirectory: "Collapse directory {name}",
  openDiff: "Open diff {path}",
  noChangedFilesMatch: "No changed files match “{query}”.",
  documentDiff: "Document diff",
  noFileSelected: "No file selected",
  fileNavigation: "File navigation",
  previousChangedFile: "Previous changed file",
  previousFile: "Previous file",
  nextChangedFile: "Next changed file",
  nextFile: "Next file",
  diffLayout: "Diff layout",
  splitDiff: "Split diff",
  unifiedDiff: "Unified diff",
  wrapLines: "Wrap lines",
  wrapLongLines: "Wrap long lines",
  chooseChangedFile: "Choose a changed file to inspect.",
  previewUnavailable: "Preview unavailable",
  sizeSummary: "Old {oldSize} · new {newSize}",
  loadingPreview: "Loading bounded preview…",
  diffRenderFailed: "Diff could not be rendered",
  diffIntegrityFailed: "Diff integrity check failed",
  retryDiffPreview: "Retry preview",
  copyDiagnostics: "Copy diagnostics",
  diagnosticsCopied: "Diagnostics copied",
  diagnosticsCopyFailed: "Diagnostics could not be copied",
  lineSummary: "{oldLines} → {newLines} lines",
  nextActionStop: "Stop continuous evolution",
  nextActionReviewEvidence: "Review the current evidence",
  criterion_hard_gates: "Hard gates",
  criterion_hard_gates_description: "Required assertions, paired evidence, and safety checks must all pass.",
  criterion_pareto: "Objective non-regression",
  criterion_pareto_description: "No declared objective may regress beyond its tolerance in any paired repeat.",
  criterion_material_improvement: "Repeat-consistent material improvement",
  criterion_material_improvement_description: "At least one primary objective must reach its declared minimum delta in every paired repeat.",
  attribution_skill: "Skill behavior",
  attribution_eval: "Eval design",
  attribution_execution_environment: "Execution environment",
  attribution_evidence: "Missing evidence",
  attribution_human: "Human decision",
  action_generate_candidate: "Generate the next candidate",
  action_prepare_audit: "Prepare and bind the release audit",
  action_rerun_execution: "Run or rerun the authorized execution",
  action_propose_eval_change: "Submit an eval change proposal",
  action_request_release_confirmation: "Request release confirmation",
  rootDirectory: "root",
} as const;

export type MessageKey = keyof typeof englishMessages;
type MessageValues = Record<string, string | number>;

const chineseMessages: Record<MessageKey, string> = {
  pageTitle: "Skill Reviewer · 决策审查",
  appTitle: "Skill Reviewer 决策审查",
  brandEvidence: "决策审查",
  displayPreferences: "显示偏好",
  language: "语言",
  switchToEnglish: "切换到英文",
  switchToChinese: "切换到中文",
  switchToDarkTheme: "切换到深色主题",
  switchToLightTheme: "切换到浅色主题",
  darkTheme: "深色",
  lightTheme: "浅色",
  textSize: "文字大小",
  decreaseTextSize: "缩小文字",
  increaseTextSize: "放大文字",
  resetTextSize: "将文字大小恢复为 100%",
  textSizeValue: "文字大小 {percent}%",
  openCommandPalette: "查找场景或证据",
  commandPaletteTitle: "查找场景或证据",
  commandPalettePlaceholder: "输入场景名称、内部 ID、文件路径或操作",
  closeCommandPalette: "关闭命令面板",
  commandsAvailable: "可用命令",
  noCommandsFound: "没有匹配的目标",
  noCommandsHint: "可尝试输入场景名称、内部 ID、证据名称或文件路径。",
  navigate: "定位",
  runCommand: "打开",
  close: "关闭",
  actionGroup: "操作",
  caseGroup: "场景",
  evidenceGroup: "证据",
  fileGroup: "文件",
  copyViewLink: "复制当前视图链接",
  downloadEvidenceJson: "下载当前评测数据",
  viewLinkCopied: "当前视图链接已复制",
  viewLinkCopyFailed: "无法复制当前视图链接",
  evidenceJsonDownloaded: "已开始下载评测数据",
  evidenceJsonDownloadFailed: "无法下载评测数据",
  showEvidence: "查看评测证据",
  showExecutionTrace: "查看 Agent 执行记录",
  showDiff: "查看 Skill 文件变更",
  showAttention: "只看需要处理的场景",
  showAllCases: "显示全部评测场景",
  useDarkTheme: "使用深色主题",
  useLightTheme: "使用浅色主题",
  useChinese: "使用简体中文",
  useEnglish: "使用英文",
  resizeCasePane: "调整评测场景栏宽度",
  resizeInspectorPane: "调整证据说明栏宽度",
  resizePaneHint: "拖动调整宽度 · 方向键微调 · 按 Enter 恢复默认",
  resetPaneWidths: "恢复默认栏宽",
  resetPaneWidthsDescription: "把评测场景栏和证据说明栏恢复为默认宽度。",
  paneWidthsReset: "已恢复默认栏宽",
  live: "已连接",
  connecting: "连接中",
  stale: "已过期",
  readOnly: "证据只读",
  releaseReady: "可以进入发布",
  hardGates: "发布门禁",
  casesPassed: "场景通过",
  round: "演进轮次",
  evidence: "证据",
  evidenceScope: "证据范围",
  runOverview: "评测概览",
  evaluationSuite: "评测场景",
  cases: "评测场景",
  split: "评测阶段",
  evaluationLifecycle: "评测流程",
  singleScenarioStageLabel: "单一场景 · {stage}",
  evolutionDetails: "演进详情",
  allStageCases: "全部场景",
  allStageFilterOption: "查看全部评测阶段；共 {count} 个场景",
  stageFilterOption: "{stage}；共 {count} 个场景",
  stagePurpose: "这个阶段做什么",
  stageOutcome: "阶段产出",
  allStagesTitle: "查看完整评测链路",
  allStagesDescription: "这里汇总开发验证、候选选拔和发布审计。“全部场景”只是查看方式，不是第四个评测阶段。",
  allStagesOutcome: "用于跨阶段总览，不会产生一条新的评测结论。",
  developmentStageShort: "找问题",
  developmentStageTitle: "低成本定位问题，指导下一版修改",
  developmentStageDescription: "迭代时可以只运行相关场景，保留的证据允许反馈给优化 Agent，用来生成下一候选。",
  developmentStageOutcome: "只产出诊断和改进信号，不能决定候选是否通过或是否发布。",
  selectionStageShort: "比新旧",
  selectionStageTitle: "把候选版与已接受旧版做完整对照",
  selectionStageDescription: "运行冻结的全部选拔场景，同时检查硬门禁、目标不退化和逐次一致的实质提升。",
  selectionStageOutcome: "通过才进入一次性发布审计；未通过则生成下一候选，最多 3 轮。",
  auditStageShort: "做终审",
  auditStageTitle: "用未参与优化的场景做一次最终复核",
  auditStageDescription: "候选通过选拔后完整运行一次，场景和结果不再反馈给优化 Agent，避免对审计集过拟合。",
  auditStageOutcome: "通过只代表行为证据满足发布条件；最终发布仍由人确认。",
  publicAuditScope: "本次是公开校准审计：它用于验证审计判断能力，不能单独支持发布。",
  opaqueAuditScope: "本次使用外部隐藏评测，可作为一次性发布审计证据。",
  searchCases: "搜索场景",
  filterCases: "按名称或 ID 筛选",
  caseStatus: "按场景结果",
  attention: "需处理场景",
  caseFilterOption: "{label}；匹配场景数：{count}",
  caseFilterScope: "此处只筛选和统计评测场景；发布门禁会在中间证据树中单独展示。",
  noCasesMatch: "当前视图没有匹配的场景。",
  clearFilters: "清除筛选",
  caseResults: "当前显示 {count} / {total} 个场景",
  all: "全部",
  development: "开发验证",
  selection: "候选选拔",
  audit: "发布审计",
  pairedRuns: "{count} 轮候选/旧版对照",
  noCasesInSplit: "当前评测阶段没有场景。",
  evolution: "连续演进",
  continuitySummary: "连续演进周期 {epoch} · 已淘汰 {count} 个候选",
  candidateLineage: "候选演进记录",
  lineageRound: "第 {round} 轮",
  evidenceWorkspace: "证据工作区",
  canvasView: "查看内容",
  reviewTab: "评审",
  changesTab: "变更",
  runsTab: "执行",
  auditTab: "证据档案",
  executionTrace: "Agent 执行记录",
  executionTraceContext: "已保留 {observed}/{expected} 次 Agent 执行",
  executionTraceKicker: "Eval 场景 → Agent 真实事件",
  executionTraceTitle: "Agent 真实执行记录",
  executionTraceDescription: "先选择 Eval 场景，再对照候选与声明的对照条件，最后查看真实记录下来的文件读取、工具调用、命令、消息、错误和输出产物。",
  traceAttentionSummary: "Trace 异常摘要",
  traceAttentionTitle: "先看异常",
  traceAttentionDescription: "优先级依次为：失败、证据缺口、候选/对照差异、异常慢执行。",
  traceFailures: "失败",
  traceFailureBreakdown: "{checks} 项检查 · {events} 条事件",
  traceEvidenceGaps: "证据缺口",
  traceComparisonDifferences: "候选/对照差异",
  traceSlowExecutions: "慢执行",
  traceSlowThreshold: "阈值 {duration}",
  traceTechnicalContext: "技术来源与执行边界",
  observableEvidenceBoundary: "这里只展示 Agent 的可观察事件",
  observableEvidenceBoundaryDescription: "这里不会用状态摘要拼出一条假的 Trace，也不会展示私有思维链；执行框架没有采集到的事件会明确显示为缺失。",
  localUnattestedTrace: "本地完全访问不等于隔离证明",
  localUnattestedTraceDescription: "本次本地 Agent 进程保留了可观察事件，但仍可能访问评测目录之外的资源。它适合分析 Agent 如何执行，不能单独证明操作系统权限或禁网策略已被强制执行。",
  selectTraceCase: "选择要核对的评测场景",
  traceCaseIndexTitle: "Eval Case 运行索引",
  traceCaseIndexDescription: "每行是一个 Eval Case；Trace 覆盖率统计候选/对照计划执行中，真正保留了 Agent 事件流的次数。",
  traceCaseColumn: "Eval Case",
  traceStageColumn: "评测阶段",
  tracePolicyColumn: "执行策略",
  traceCoverageColumn: "真实 Trace",
  traceDurationColumn: "累计耗时",
  traceStatusColumn: "场景结论",
  deterministicRunPolicy: "每个实验臂执行 1 次",
  stochasticRunPolicy: "每个实验臂独立执行 {count} 次",
  capturedAgentTraces: "已采集真实 Trace",
  selectedEvalCase: "当前 Eval 场景",
  traceResponsibilityTitle: "这条记录由谁执行、记录什么",
  leadAgentRole: "主 Agent",
  leadDispatchesWorker: "主 Agent 负责分发，评测执行 Agent 负责运行",
  leadAgentTraceBoundary: "主 Agent 使用 Skill Reviewer 锁定计划，并分发每个场景/实验臂/重复执行单元；治理决策保留在运行产物中，不作为被评测行为计分。",
  evalWorkerRole: "评测执行 Agent",
  nativeSubagent: "Host 已观测的原生子 Agent",
  localAgentProcess: "已观测进程的本地 Agent",
  declaredAgentProfile: "仅声明的执行器配置",
  externalAgentHarness: "外部 Agent 执行器",
  executorNotRecorded: "未记录评测执行 Agent",
  evalWorkerTraceBoundary: "它才是当前 Trace 的评测主体：候选臂使用锁定候选 Skill；对照臂使用声明的旧版 Skill 或不使用 Skill。可观察的文件、工具、命令、消息、错误与输出共同组成真实 Trace。",
  declaredExecutorBoundary: "当前运行声明了这类执行器，但所选执行没有有效的 Agent 或 harness 调度凭据。这里只能视为配置，不能证明该 Agent 确实运行过。",
  dispatchReceipt: "调度凭据",
  sourceTrace: "源事件流",
  sourceAgent: "来源 Agent",
  adapterProvenance: "适配器来源证明",
  dispatchReceiptMissing: "执行者身份尚未绑定调度凭据",
  dispatchReceiptMissingDescription: "执行配置只说明计划由谁运行；只有有效调度凭据才能把当前记录标识为原生子 Agent 或本地 Agent 进程。",
  nestedAgentTraceCaptured: "已声明可采集下级 Agent 事件",
  nestedAgentTraceNotCaptured: "这条 Trace 未声明包含下级 Agent 行为",
  nestedAgentTraceBoundary: "如果被评测 Skill 再启动其他 Agent，只展示执行框架真实采集到的子事件；未采集的行为不会被推测补全。",
  selectRepeat: "选择执行轮次",
  executionMatrixTitle: "执行矩阵",
  executionMatrixDescription: "每行是一次独立重复执行，每列是严格隔离的实验臂；选择一个已保留单元，查看它的真实 Trace。",
  repeatColumn: "重复执行",
  repeatNotEvolutionRound: "第 {repeat} 次是同一锁定场景的独立执行，不是第 {repeat} 轮 Skill 演进。",
  executionMissing: "执行记录缺失",
  traceCaptured: "已采集 Trace",
  traceNotCaptured: "Trace 缺失",
  executionCellLabel: "{arm} · 第 {repeat} 次执行 · {status}",
  assertionScore: "检查 {passed}/{total}",
  eventTimeline: "可观察事件时间线",
  eventTimelineDescription: "事件按采集顺序排列；展开事件可查看真实载荷和关联产物。",
  realTraceMissing: "这次执行没有采集真实 Agent Trace",
  realTraceMissingDescription: "执行状态摘要不能代替 Trace。请开启框架原生采集或由主 Agent 记录可观察事件后，重新运行这个 Eval 场景。",
  captureSource: "采集来源",
  capturedEvents: "事件数",
  duration: "耗时",
  traceDigest: "Trace 摘要",
  eventSequence: "事件 {sequence}",
  noEventDetails: "这条事件没有更多可观察载荷。",
  artifactReferences: "关联产物",
  checksAndJudge: "检查项与 Judge 结论",
  checksAndJudgeDescription: "看完真实执行后，再核对确定性检查和语义 Judge 如何使用保留产物作出结论。",
  linkedTraceEvents: "关联 {count} 条 Trace 事件",
  locateTraceEvent: "定位 Trace",
  semanticJudgeResults: "匿名语义 Judge",
  semanticJudgeResultsDescription: "评审结论严格绑定具体输出摘要，以及生成这些输出的 Trace 事件。",
  judgePreference: "偏好结论",
  noCheckComparison: "这个场景没有保留可成对对照的检查结果。",
  lockedEvalDefinition: "已锁定的 Eval 绑定",
  manifestDigest: "evals.json 摘要",
  planDigest: "锁定计划摘要",
  determinism: "执行策略",
  deterministicAssertions: "确定性检查",
  semanticAssertions: "语义检查",
  failedChecks: "未通过检查",
  candidateLane: "待评候选版本",
  baselineLane: "对照条件",
  comparisonConclusion: "对比结论",
  comparison_candidate_improved: "候选通过，对照未通过",
  comparison_candidate_regressed: "候选未通过，对照通过",
  comparison_both_passed: "候选与对照均通过",
  comparison_both_failed: "候选与对照均未通过",
  comparison_mixed: "重复执行结果存在分歧",
  comparison_incomplete: "至少一个实验臂缺少证据",
  comparison_unpaired: "当前没有可用的成对对照",
  repeatObservation: "第 {repeat} 次",
  missingArmObservation: "该实验臂没有保留对应观测",
  armEvidenceGroup: "版本证据对照",
  candidateEvidenceDescription: "左侧展示候选版的执行、检查和产物。",
  baselineEvidenceDescription: "右侧展示声明对照条件的执行、检查和产物。",
  armEvidenceSummary: "检查通过 {passed}/{total} · 产物 {artifacts} 个",
  pairedEvidenceRegion: "候选与对照条件的配对证据",
  pairedEvidenceLayoutDescription: "每一行对齐同一个检查或产物，无需上下翻找即可看出两版结果差异。",
  pairedEvidenceItems: "{count} 组逐项证据",
  itemByItemComparison: "逐项对照",
  evidenceComparisonSame: "结果一致",
  evidenceComparisonDifferent: "结果不同",
  evidenceComparisonMissing: "证据缺失",
  candidateEvidenceMissing: "没有保留与当前对照条件匹配的候选证据。",
  baselineEvidenceMissing: "没有保留与当前候选匹配的对照证据。",
  diff: "文件差异",
  diffEvidenceMissing: "文件差异 · 未捕获修改证据",
  displayedEvidenceNodes: "当前显示 {visible} / {total} 条证据",
  runtimeFilesChanged: "{count} 个 Skill 文件发生变更",
  enterDiffFocus: "进入差异专注模式",
  exitDiffFocus: "退出差异专注模式",
  focusOnDiff: "专注查看文件差异",
  exitFocus: "退出专注查看",
  immutableRunRecord: "可追溯评测记录",
  evidenceChainDescription: "先看发布结论，再打开失败场景与未通过检查，最后阅读它实际使用的原始证据。",
  reviewOverview: "评审总览",
  problemsToFix: "需要解决的问题",
  primaryBlockerLabel: "首要阻塞",
  openValidityStepEvidence: "打开{step}对应的判定证据",
  openObjectiveCaseEvidence: "打开 {title} 的场景证据",
  verificationLevelLabel: "证据",
  runStateLabel: "运行状态",
  releaseBlockerCount: "需要处理的独立问题：{count}",
  releaseBlockerNone: "当前保留证据中没有发布阻塞项。",
  noKnownBlockerEvidenceIncomplete: "未发现已知阻塞，但发布证据不完整",
  evidenceIncompleteReleaseBlocked:
    "暂不可发布。请先补齐所需的发布证据，再形成最终判断。",
  notConfigured: "未配置",
  criterionFailedSummary: "满足 {passed}/{total} 项，这个接受条件未通过。",
  criterionEvidenceUnavailable: "这项条件没有保留可直接核对的有界证据。",
  issueWhy: "为什么没有通过",
  issueNextStep: "应该怎么处理",
  issueAction_skill: "修正 Skill 的指令或行为，然后重新运行这个场景。",
  issueAction_eval: "提交 Eval 修改建议，等待用户确认后再建立新运行。",
  issueAction_execution_environment: "修复执行配置或输入绑定，然后重新运行。",
  issueAction_evidence: "补齐候选版或对照版证据，然后重新运行。",
  issueAction_human: "请评审人完成当前所需的授权或确认。",
  issueEvidenceCount: "可核对 {count} 条已保留证据。",
  issueEvidenceSummary: "{checks} 项检查未通过 · {sources} 份原始产物",
  scenarioDidNotPass: "评测场景没有通过",
  openProblemEvidence: "查看这个问题的判定证据",
  readyForHumanConfirmation: "自动检查没有发现阻塞项；是否发布仍由人最终确认。",
  automaticNoBlockerSummary: "未发现已知阻塞，但发布证据不完整，暂不可发布；主 Agent 会自动进入下一个已锁定的评测阶段。",
  noFailedCheckRecorded: "没有保留候选版失败检查；请从场景或门禁证据核对是否缺少输入、基线或判定条件。",
  decisionCoverage: "判断覆盖情况",
  decisionEvidence: "决策证据",
  whatChanged: "改了什么",
  changeEvidenceCount: "已捕获 {count} 个变更文件",
  noChangeEvidenceCaptured: "未捕获修改证据",
  evidenceCoverage: "证据覆盖",
  evidenceCoverageRatio: "已核验 {captured}/{expected} 次执行",
  decisionValidity: "决策有效性",
  decisionValidityDescription: "先信证据，再信测量，最后才评价 Skill。",
  evidenceIntegrity: "证据完整性",
  evidenceIntegrityValid: "绑定与 Trace 已验证",
  evidenceIntegrityInvalid: "证据完整性未通过",
  measurementValidity: "测量有效性",
  measurementValid: "判据与采样已验证",
  measurementInvalid: "测量无效",
  measurementUnverified: "测量尚未验证",
  measurementPending: "等待测量预检",
  candidateQuality: "候选质量",
  candidateAccepted: "选拔已接受",
  candidateRejected: "候选未接受",
  candidatePending: "候选结论待定",
  candidateNotJudged: "暂不评价 Skill",
  objectiveEvidence: "目标对照",
  objectiveEvidenceTitle: "可测行为究竟发生了什么变化",
  objectiveEvidenceDescription: "方向归一化差值逐次对比候选版与已接受基线；正值代表候选更好。重复结果用于观察一致性，不代表统计置信度。",
  objectiveMeanDelta: "平均 Δ",
  objectiveBaselineValue: "基线实际值",
  objectiveCandidateValue: "候选实际值",
  objectivePairedDeltas: "逐次配对 Δ",
  objectiveRepeatCount: "n = {count}",
  objectiveGuardrails: "预先声明阈值",
  objectiveGuardrailValues: "不退化 ≥ {tolerance} · 实质提升 ≥ {material}",
  objectiveRegressionObserved: "发现退化",
  objectiveMaterialEveryRepeat: "每次配对均达到实质提升",
  objectiveNonRegressedOnly: "未退化，但实质提升不具备逐次一致性",
  noKnownRisk: "未发现已知发布风险",
  evidenceIncomplete: "发布证据不完整",
  reviewChangeEvidence: "查看修改证据",
  reviewExecutionEvidence: "查看执行证据",
  reviewPrimaryRiskEvidence: "查看主要风险证据",
  recommendedNextStep: "建议下一步",
  auditArchive: "完整审计记录",
  auditArchiveDescription: "用于复现和审计的技术证据索引。日常 Review 不需要逐条点开，只有核对具体观察或产物时再展开。",
  evidenceTreeControls: "评测证据树控制",
  evidenceHierarchy: "评测证据树",
  expandAllEvidence: "全部展开",
  collapseAllEvidence: "全部收起",
  expandEvidence: "展开 {label}",
  collapseEvidence: "收起 {label}",
  statusLegend: "结论图例",
  passed: "通过",
  pending: "待确认",
  blocked: "阻塞",
  openEvidence: "打开证据 {label}",
  childItems: "{count} 条下级证据",
  repeatMeta: "第 {count} 轮执行",
  loadingDiffRenderer: "正在准备文件差异视图…",
  noRuntimeChanges: "未捕获修改证据",
  candidateMatchesRuntime: "当前 projection 没有变更产物。这代表证据缺口，不能据此断言没有发生修改。",
  evidenceInspector: "证据详情",
  inspector: "证据说明",
  retainedEvidenceDescription: "本次评测保留的原始证据，可用于复查和审计。",
  currentFinding: "当前结论",
  decisionBasis: "为什么是这个结果",
  nextReviewStep: "下一步怎么核对",
  viewBasisEvidence: "查看证据",
  whyItMatters: "为什么要看",
  evidenceInputs: "它读取了什么",
  reviewerChecklist: "人工 Review 应该看什么",
  importance: "对结论的影响",
  sourceEvidence: "原始证据内容",
  sourceEvidenceDescription: "这是该检查实际读取、或该结论直接引用的保留内容。",
  loadingSourceEvidence: "正在读取保留证据…",
  sourceEvidenceUnavailable: "当前视图无法直接读取这份证据内容。",
  sourceEvidenceLoadFailed: "无法读取保留内容，或文件已不再匹配锁定摘要。",
  opaqueEvidence: "这是隐藏审计场景，内容不会在此公开，避免连续演进过程针对留出集调参。",
  binaryEvidence: "这是一份二进制证据，系统通过摘要校验，而不在页面中直接渲染。",
  oversizedEvidence: "该证据超过安全的页面内阅读上限；仍可在技术追溯信息中核对路径和摘要。",
  evidencePreview: "证据预览",
  evidenceViewMode: "证据查看方式",
  structuredPreview: "结构化",
  renderedPreview: "预览",
  sourceView: "源码",
  jsonLineRecords: "JSONL 记录",
  jsonRoot: "JSON 文档",
  jsonLinesFormat: "JSON Lines",
  plainTextFormat: "纯文本",
  markdownImageNotLoaded: "图片未自动加载：{alt}",
  unnamedImage: "未命名图片",
  closeEvidencePreview: "关闭证据预览",
  evidenceDigestBound: "内容已与保留摘要完成校验。",
  evidencePreviewHint: "在阅读浮层中查看完整、可滚动的证据内容。",
  openFullPreview: "打开完整预览",
  contentTruncated: "页面只展示有界预览；完整文件仍由摘要锁定。",
  evidenceSize: "已保留 {size} 字节",
  evidenceId: "证据标识",
  arm: "对照版本",
  repeat: "执行轮次",
  assertion: "检查方式",
  artifactPath: "产物路径",
  decisionArtifact: "决策产物",
  technicalTrace: "技术追溯信息",
  technicalName: "内部名称",
  pairedArms: "候选版与旧版对照",
  missingObjectiveMetrics: "暂时无法判定，缺少客观指标：{metrics}",
  assertionsSummary: "必检项通过 {passed}/{total} · 通过率 {rate}",
  bindingSummary: "输入绑定错误 {binding} 项 · 禁止操作 {forbidden} 项 · 外部副作用 {effects} 项",
  semanticEvidence: "匿名语义评审",
  preference: "评审更偏好：{value}",
  unresolved: "尚无一致结论",
  provenance: "本次如何执行",
  subject: "被审查 Skill",
  subjectFingerprint: "被审查 Skill 指纹",
  baseline: "对照版本",
  baselineFingerprint: "对照版本指纹",
  plan: "评测计划指纹",
  profile: "执行配置指纹",
  target: "执行主体",
  harness: "分发方式",
  holdout: "场景可见性",
  controlAnchor: "演进状态锚点",
  none: "无",
  unknown: "未知",
  public: "公开可见",
  notUsed: "未使用",
  notRecorded: "未记录",
  selectEvidence: "请从中间的评测证据树中选择一条记录。",
  limitations: "当前限制",
  noLimitations: "当前没有已知限制。",
  refreshEvery: "每 {seconds} 秒",
  generatedAt: "评测生成于 {time}",
  loadedAt: "上次刷新 {time}",
  attemptedAt: "上次尝试 {time}",
  notChecked: "尚未检查",
  pauseAutoRefresh: "暂停自动刷新",
  resumeAutoRefresh: "恢复自动刷新",
  refreshDashboard: "立即刷新 Dashboard",
  autoRefreshOn: "检查投影更新",
  autoRefreshPaused: "自动刷新已暂停",
  lastRefreshFailed: "最近一次刷新失败",
  connectingToEvidence: "正在连接评测证据",
  waitingForData: "正在等待评测结果数据…",
  dashboardDataIncompatible: "Dashboard 数据版本不兼容",
  dashboardDataRegenerateHelp:
    "请使用当前 skill-reviewer runtime 重新生成 dashboard-data.json，然后刷新此页面。",
  dashboardRenderFailed: "Dashboard 无法渲染当前 projection",
  dashboardRenderRecovery:
    "请使用当前 skill-reviewer runtime 重新生成 dashboard-data.json，然后重新加载此页面。",
  reloadDashboard: "重新加载 Dashboard",
  evidenceUnavailable: "无法读取评测证据",
  retryConnection: "重新连接",
  retryHelp: "请确认只读 Dashboard 服务已启动，然后重新连接。",
  skipToEvidence: "跳转到证据工作区",
  copyEvidenceReference: "复制证据引用",
  evidenceReference: "Skill Reviewer 证据引用",
  semanticSummary: "证据含义",
  evidenceReferenceCopied: "证据引用已复制",
  evidenceReferenceCopyFailed: "无法复制证据引用",
  status: "结论状态",
  permalink: "直达链接",
  changedFileTree: "变更文件",
  changedFilesRoot: "SKILL-REVIEWER",
  expandChangedFilesRoot: "展开变更文件根目录",
  collapseChangedFilesRoot: "收起变更文件根目录",
  filterChangedFiles: "筛选变更文件",
  filterFiles: "筛选文件",
  changedRuntimeFileTree: "本次变更的 Skill 文件目录",
  expandDirectory: "展开目录 {name}",
  collapseDirectory: "收起目录 {name}",
  openDiff: "打开差异 {path}",
  noChangedFilesMatch: "没有变更文件匹配“{query}”。",
  documentDiff: "文档差异",
  noFileSelected: "未选择文件",
  fileNavigation: "文件导航",
  previousChangedFile: "上一个变更文件",
  previousFile: "上一个文件",
  nextChangedFile: "下一个变更文件",
  nextFile: "下一个文件",
  diffLayout: "差异布局",
  splitDiff: "左右对比",
  unifiedDiff: "合并对比",
  wrapLines: "自动换行",
  wrapLongLines: "长行自动换行",
  chooseChangedFile: "选择一个变更文件进行检查。",
  previewUnavailable: "当前文件无法预览",
  sizeSummary: "修改前 {oldSize} · 修改后 {newSize}",
  loadingPreview: "正在加载受限预览…",
  diffRenderFailed: "无法渲染差异",
  diffIntegrityFailed: "差异完整性校验失败",
  retryDiffPreview: "重试预览",
  copyDiagnostics: "复制诊断信息",
  diagnosticsCopied: "诊断信息已复制",
  diagnosticsCopyFailed: "无法复制诊断信息",
  lineSummary: "{oldLines} → {newLines} 行",
  nextActionStop: "停止连续演进",
  nextActionReviewEvidence: "人工复核当前证据",
  criterion_hard_gates: "硬门禁",
  criterion_hard_gates_description: "必需断言、成对证据和执行安全检查必须全部通过。",
  criterion_pareto: "目标不退化",
  criterion_pareto_description: "每次配对执行中，所有已声明目标都不能超过容忍阈值发生退化。",
  criterion_material_improvement: "逐次一致的实质提升",
  criterion_material_improvement_description: "至少一个主要目标必须在每次配对执行中达到预先声明的最小提升幅度。",
  attribution_skill: "Skill 行为",
  attribution_eval: "Eval 设计",
  attribution_execution_environment: "执行环境",
  attribution_evidence: "证据缺失",
  attribution_human: "人工裁决",
  action_generate_candidate: "生成下一候选",
  action_prepare_audit: "准备并绑定发布审计",
  action_rerun_execution: "执行或重跑已授权场景",
  action_propose_eval_change: "提交 Eval 修改建议",
  action_request_release_confirmation: "请求发布确认",
  rootDirectory: "Skill 根目录",
};

const messages: Record<Locale, Record<MessageKey, string>> = {
  en: englishMessages,
  "zh-CN": chineseMessages,
};

const statusLabels: Record<string, string> = {
  passed: "通过",
  accepted: "候选已保留",
  "audit-passed": "发布审计通过",
  retained: "证据已保留",
  "regression-verified": "已完成新旧版对照验证",
  "behavior-verified": "已完成真实行为验证",
  failed: "未通过",
  rejected: "候选已淘汰",
  regressed: "质量发生退化",
  "audit-failed": "发布审计未通过",
  invalid: "评测数据无效",
  stale: "证据已过期",
  disagreement: "评审存在分歧",
  blocked: "已阻塞",
  pending: "待确认",
  "awaiting-audit": "待自动执行发布审计",
  inconclusive: "证据不足",
  incomplete: "证据不完整",
  missing: "证据缺失",
  mixed: "结果不一致",
  "no-change": "无有效改进",
  exhausted: "已用完演进轮次",
  completed: "已完成",
  running: "执行中",
  optimizing: "持续优化中",
  agreement: "评审结论一致",
  "measurement-invalid": "测量无效，无法评价候选",
  "measurement-unverified": "测量尚未验证",
  "not-run": "未执行",
  planned: "已计划未执行",
};

const valueLabels: Record<string, string> = {
  development: "开发验证",
  selection: "候选选拔",
  audit: "发布审计",
  deterministic: "确定性执行 1 次",
  stochastic: "随机性成对执行",
  public: "公开可见",
  opaque: "隐藏评测",
  "public-calibration": "公开校准场景",
  "opaque-holdout": "隐藏评测场景",
  old_skill: "旧版 Skill",
  with_skill: "候选版 Skill",
  candidate: "候选版 Skill",
  without_skill: "未使用 Skill",
  baseline: "对照版本",
  "native-agent": "由主 Agent 直接执行",
  "lead-agent-dispatch": "由主 Agent 负责分发",
  "trusted-orchestrator": "由可信编排器隔离执行",
  "local-unattested": "本地执行（未提供隔离证明）",
  "danger-full-access": "完全访问模式",
  "jsonl-agent-events": "Agent JSONL 可观察事件",
  "source-event-stream": "Agent 可观察源事件流",
  "orchestrator-default": "遵循编排器默认采样策略",
  "local/trusted": "本地可信存储",
  harness_native: "执行框架原生采集",
  lead_agent_observed: "主 Agent 可观察记录",
  provider_stream: "Agent 源事件适配器采集",
  execution_started: "开始执行",
  file_read: "读取文件",
  tool_call: "调用工具",
  command: "执行命令",
  agent_message: "Agent 可见消息",
  artifact_written: "生成产物",
  error: "执行错误",
  execution_finished: "结束执行",
  tool: "工具",
  path: "路径",
  argv: "命令参数",
  cwd: "工作目录",
  exit_code: "退出码",
  stdout: "标准输出",
  stderr: "错误输出",
  aggregated_output: "合并输出",
  source_event_index: "来源事件序号",
  source_event_type: "来源事件类型",
  source_item_id: "来源执行项 ID",
  source_item_type: "来源执行项类型",
  thread_id: "来源会话 ID",
  usage: "Token 用量",
  sandbox_mode: "Agent 沙箱模式",
  approval_policy: "人工批准策略",
  isolation_claim: "隔离证据级别",
  permission_enforcement: "权限约束方式",
  ambient_skills_disabled: "已禁用环境 Skill 数",
  source_stream_digest: "Agent 源事件流摘要",
  redaction: "隐私删减规则",
  result_summary: "结果摘要",
  content: "可见内容",
  role: "消息角色",
  digest: "内容摘要",
  size: "文件大小",
  file_exists: "检查必需文件是否存在",
  text_contains: "检查必需信息是否完整",
  text_matches: "检查结论表达是否符合要求",
  text_not_matches: "检查是否匹配无依据结论",
  text_not_contains: "检查是否出现无依据结论",
  semantic_pair: "匿名比较候选版与旧版",
  continue: "延续上一轮",
  reset: "重新开始",
  propose_candidate: "生成下一候选",
  run_authorized_selection: "执行已绑定的候选选拔",
  run_authorized_audit: "执行已绑定的发布审计",
  prepare_audit: "自动准备发布审计",
  request_user_release: "请求人工发布确认",
  review_evidence: "人工复核当前证据",
  stop: "停止连续演进",
  lead_agent: "主 Agent",
  added: "新增",
  removed: "删除",
  modified: "修改",
  run: "评测运行",
  gate: "发布门禁",
  iteration: "演进轮次",
  case: "评测场景",
  assertion: "检查项",
  artifact: "证据文件",
};

export function translate(
  locale: Locale,
  key: MessageKey,
  values: MessageValues = {},
): string {
  return messages[locale][key].replace(/\{(\w+)\}/g, (_, name: string) =>
    String(values[name] ?? `{${name}}`),
  );
}

export function localizeStatus(locale: Locale, status: string): string {
  return locale === "zh-CN" ? (statusLabels[status] ?? status) : status;
}

export function localizeValue(locale: Locale, value: string): string {
  return locale === "zh-CN" ? (valueLabels[value] ?? value) : value;
}

interface UiPreferences {
  locale: Locale;
  theme: Theme;
  fontScale: FontScale;
  setLocale: (locale: Locale) => void;
  setTheme: (theme: Theme) => void;
  setFontScale: (fontScale: FontScale) => void;
  t: (key: MessageKey, values?: MessageValues) => string;
}

const UiPreferencesContext = createContext<UiPreferences | null>(null);

function readStoredPreference<T extends string>(
  key: string,
  allowed: readonly T[],
): T | null {
  try {
    const value = window.localStorage.getItem(key);
    return allowed.includes(value as T) ? (value as T) : null;
  } catch {
    return null;
  }
}

function initialLocale(): Locale {
  return (
    readStoredPreference(preferenceStorageKeys.locale, ["en", "zh-CN"]) ??
    (window.navigator.language.toLowerCase().startsWith("zh") ? "zh-CN" : "en")
  );
}

function initialTheme(): Theme {
  return (
    readStoredPreference(preferenceStorageKeys.theme, ["light", "dark"]) ??
    (window.matchMedia?.("(prefers-color-scheme: dark)").matches ? "dark" : "light")
  );
}

function initialFontScale(): FontScale {
  const stored = readStoredPreference(
    preferenceStorageKeys.fontScale,
    fontScaleOptions.map(String),
  );
  return stored ? (Number(stored) as FontScale) : 1;
}

export function UiPreferencesProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(initialLocale);
  const [theme, setTheme] = useState<Theme>(initialTheme);
  const [fontScale, setFontScale] = useState<FontScale>(initialFontScale);

  useLayoutEffect(() => {
    document.title = translate(locale, "pageTitle");
    document.documentElement.lang = locale;
    document.documentElement.dataset.theme = theme;
    document.documentElement.dataset.fontScale = String(
      Math.round(fontScale * 100),
    );
    document.documentElement.style.colorScheme = theme;
    document.documentElement.style.setProperty("--ui-scale", String(fontScale));
    document.documentElement.style.setProperty(
      "--ui-scale-inverse",
      (1 / fontScale).toFixed(6),
    );
    try {
      window.localStorage.setItem(preferenceStorageKeys.locale, locale);
      window.localStorage.setItem(preferenceStorageKeys.theme, theme);
      window.localStorage.setItem(
        preferenceStorageKeys.fontScale,
        String(fontScale),
      );
    } catch {
      // Preferences remain valid for the current session when storage is unavailable.
    }
  }, [fontScale, locale, theme]);

  useEffect(() => {
    const syncPreference = (event: StorageEvent) => {
      if (event.key === preferenceStorageKeys.locale && ["en", "zh-CN"].includes(event.newValue ?? "")) {
        setLocale(event.newValue as Locale);
      }
      if (event.key === preferenceStorageKeys.theme && ["light", "dark"].includes(event.newValue ?? "")) {
        setTheme(event.newValue as Theme);
      }
      if (
        event.key === preferenceStorageKeys.fontScale &&
        fontScaleOptions.map(String).includes(event.newValue ?? "")
      ) {
        setFontScale(Number(event.newValue) as FontScale);
      }
    };
    window.addEventListener("storage", syncPreference);
    return () => window.removeEventListener("storage", syncPreference);
  }, []);

  const value = useMemo<UiPreferences>(
    () => ({
      locale,
      theme,
      fontScale,
      setLocale,
      setTheme,
      setFontScale,
      t: (key, values) => translate(locale, key, values),
    }),
    [fontScale, locale, theme],
  );

  return (
    <UiPreferencesContext.Provider value={value}>
      {children}
    </UiPreferencesContext.Provider>
  );
}

export function useUiPreferences(): UiPreferences {
  const preferences = useContext(UiPreferencesContext);
  if (!preferences) {
    throw new Error("useUiPreferences must be used inside UiPreferencesProvider");
  }
  return preferences;
}
